# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Emailkasten - a open-source self-hostable email archiving server
# Copyright (C) 2024  David & Philipp Aderbauer
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
"""Django settings for Emailkasten project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from __future__ import annotations

import sys
from pathlib import Path

import tomli
from django.utils.translation import gettext_lazy as _
from environ import FileAwareEnv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(BASE_DIR / "src"))

# Get environ either from environment and file defined via _FILE env-variable
# See https://django-environ.readthedocs.io/en/latest/tips.html#docker-style-file-based-variables
env = FileAwareEnv()
env.read_env(BASE_DIR / ".env")

with open(BASE_DIR / "pyproject.toml", "rb") as f:
    config = tomli.load(f)

VERSION = config["project"]["version"]

# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/ for safe settings

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", cast=list, default=["localhost"])
if "localhost" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("localhost")


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "rest_framework",
    "rest_framework.authtoken",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.humanize",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_filters",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.usersessions",
    "dj_rest_auth",
    "robots",
    "constance",
    "constance.backends.database",
    "health_check",
    "health_check.db",
    "health_check.storage",
    "health_check.cache",
    "django_bootstrap5",
    "crispy_forms",
    "crispy_bootstrap5",
    "fontawesomefree",
    "health_check.contrib.migrations",
    "health_check.contrib.psutil",
    "health_check.contrib.rabbitmq",
    "health_check.contrib.celery",
    "health_check.contrib.celery_ping",
    "django_celery_results",
    "django_celery_beat",
    "Emailkasten",
    "core",
    "api",
    "web",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "api.v1.pagination.Pagination",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}

MIDDLEWARE = [
    "Emailkasten.middleware.DBReconnectMiddleware.DBReconnectMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "Emailkasten.middleware.TimezoneMiddleware.TimezoneMiddleware",
]

ROOT_URLCONF = "Emailkasten.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "src" / "Emailkasten" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "constance.context_processors.config",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_FAIL_SILENTLY = not DEBUG

WSGI_APPLICATION = "Emailkasten.wsgi.application"

SITE_ID = 1


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DATABASE", default="email_archive_django"),
        "USER": env("DATABASE_USER", default="user"),
        "PASSWORD": env("DATABASE_PASSWORD", default="passwd"),
        "HOST": "db",
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}
DATABASE_RECONNECT_RETRIES_DEFAULT = 10
DATABASE_RECONNECT_RETRIES = env(
    "DATABASE_RECONNECT_RETRIES", cast=int, default=DATABASE_RECONNECT_RETRIES_DEFAULT
)

DATABASE_RECONNECT_DELAY_DEFAULT = 10
DATABASE_RECONNECT_DELAY = env(
    "DATABASE_RECONNECT_DELAY", cast=int, default=DATABASE_RECONNECT_DELAY_DEFAULT
)
CONN_MAX_AGE = 3600
CONN_HEALTH_CHECKS = True

# Storage
STORAGE_PATH = "/mnt/archive"

STORAGES = {
    "default": {
        "BACKEND": "core.backends.ShardedFileSystemStorage.ShardedFileSystemStorage",
        "OPTIONS": {
            "location": STORAGE_PATH,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Celery
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672//"
BROKER_URL = CELERY_BROKER_URL  # required for rabbitmq django-healthcheck

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

STRICT_PASSWORDS_DEFAULT = True
AUTH_PASSWORD_VALIDATORS = (
    [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]
    if env("STRICT_PASSWORDS", cast=bool, default=STRICT_PASSWORDS_DEFAULT)
    else []
)

# Authentication
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

LOGIN_REDIRECT_URL = "web:dashboard"
LOGOUT_REDIRECT_URL = "account_login"

LOGIN_URL = "account_login"
SESSION_COOKIE_AGE = 2419200
LANGUAGE_COOKIE_AGE = SESSION_COOKIE_AGE
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_SECURE = not DEBUG
LANGUAGE_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG

# Registration
REGISTRATION_ENABLED_DEFAULT = False
REGISTRATION_ENABLED = env(
    "REGISTRATION_ENABLED", cast=bool, default=REGISTRATION_ENABLED_DEFAULT
)

# django-allauth
ACCOUNT_SIGNUP_FIELDS = ["username*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_ADAPTER = "Emailkasten.utils.toggle_signup.ToggleSignupAccountAdapter"

# dj-rest-auth
REST_AUTH = {
    "USE_JWT": False,
    "REGISTER_PERMISSION_CLASSES": (
        ("Emailkasten.utils.toggle_signup.ToggleSignUpPermissionClass",)
    ),
}

# django-robots  https://django-robots.readthedocs.io/en/latest/
ROBOTS_USE_SITEMAP = False
ROBOTS_USE_HOST = False

# Logging   https://docs.djangoproject.com/en/5.2/topics/logging/
LOG_DIRECTORY_PATH = Path(env("LOG_DIRECTORY_PATH", default="/var/log/emailkasten"))
LOGFILE_MAXSIZE_DEFAULT = 10485760
LOGFILE_MAXSIZE = env("LOGFILE_MAXSIZE", cast=int, default=LOGFILE_MAXSIZE_DEFAULT)
LOGFILE_BACKUP_NUMBER_DEFAULT = 5
LOGFILE_BACKUP_NUMBER = env(
    "LOGFILE_BACKUP_NUMBER", cast=int, default=LOGFILE_BACKUP_NUMBER_DEFAULT
)
LOGLEVEL_DEFAULT = "INFO"
LOGFORMAT = "{asctime} {levelname} - {name}.{funcName}: {message}"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": LOGFORMAT,
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
        "django_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "django.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "celery_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "celery.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "emailkasten_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "emailkasten.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "core_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "core.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "api_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "api.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "web_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "web.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
    },
    "root": {
        "handlers": ["console", "emailkasten_logfile"],
        "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
    },
    "loggers": {
        "django": {
            "handlers": ["console", "django_logfile"],
            "level": env("DJANGO_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": False,
        },
        # "celery": {
        #     "handlers": ["console", "celery_logfile"],
        #     "level": env("CELERY_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
        #     "propagate": False,
        # },
        "core": {
            "handlers": ["core_logfile"],
            "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": True,
        },
        "api": {
            "handlers": ["api_logfile"],
            "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": True,
        },
        "web": {
            "handlers": ["web_logfile"],
            "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": True,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = "en"


LANGUAGES = [
    ("ar", "العربية الفصحى"),
    ("az", "Azərbaycan dili"),
    ("bg", "Български"),
    ("ca", "català"),
    ("cs", "čeština"),
    ("da", "dansk"),
    ("de", "Deutsch"),
    ("el", "ελληνικά"),
    ("en", "English"),
    ("es", "español"),
    ("et", "eesti keel"),
    ("eu", "Euskara"),
    ("fa", "فارسی"),
    ("fi", "suomi"),
    ("fr", "français"),
    ("he", "עברית"),
    ("hr", "hrvatski"),
    ("hu", "magyar"),
    ("id", "Bahasa Indonesia"),
    ("it", "italiano"),
    ("ja", "日本語"),
    ("ka", "ქართული ენა"),
    ("ko", "한국어 [韓國語]"),
    ("ky", "Кыргыз тили"),
    ("lt", "lietuvių kalba"),
    ("lv", "latviešu valoda"),
    ("mn", "монгол"),
    ("nb", "norsk"),
    ("nl", "Nederlands"),
    ("pl", "polski"),
    ("pt-BR", "Português (Brasil)"),
    ("pt-PT", "Português (Portugal)"),
    ("ro", "română"),
    ("ru", "Русский"),
    ("sk", "slovenčina"),
    ("sl", "slovenščina"),
    ("sr", "српски / srpski"),
    ("sr-Latn", "српски / srpski (Latin)"),
    ("sv", "svenska"),
    ("th", "ภาษาไทย"),
    ("tr", "Türkçe"),
    ("uk", "українська мова"),
    ("zh-hans", "簡體中文"),
    ("zh-hant", "繁體中文"),
]


# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# On Unix systems, a value of None will cause Django to use the same
# timezone as the operating system.

USE_TZ = True
TIME_ZONE = "UTC"  # changing this doesn't change the celery schedule https://django-celery-beat.readthedocs.io/en/latest/#important-warning-about-time-zones

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [
    BASE_DIR / "src" / "Emailkasten" / "locale",
    BASE_DIR / "src" / "core" / "locale",
    BASE_DIR / "src" / "api" / "locale",
    BASE_DIR / "src" / "web" / "locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

# DRF Spectacular

SPECTACULAR_SETTINGS = {
    "TITLE": _("Emailkasten API"),
    "DESCRIPTION": _("The API schema for the Emailkasten server."),
    "VERSION": VERSION,
    "SERVE_INCLUDE_SCHEMA": True,
}

# Constance settings

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True

CONSTANCE_ADDITIONAL_FIELDS = {
    "array": ["django.forms.fields.CharField", {"widget": "django.forms.Textarea"}],
    "json": ["django.forms.fields.CharField", {"widget": "django.forms.Textarea"}],
}

CONSTANCE_CONFIG = {
    "API_DEFAULT_PAGE_SIZE": (
        20,
        _("Default page size for paginated API response data"),
        int,
    ),
    "API_MAX_PAGE_SIZE": (
        200,
        _("Maximum page size for paginated API response data"),
        int,
    ),
    "WEB_DEFAULT_PAGE_SIZE": (
        25,
        _("Default page size for pagination in the webapp."),
        int,
    ),
    "WEB_PAGE_SIZES_OPTIONS": (
        [10, 25, 50, 75, 100],
        _(
            "Page size options for pagination in the webapp. Should contain the WEB_DEFAULT_PAGE_SIZE value."
        ),
        "array",
    ),
    "DAEMON_CYCLE_PERIOD_DEFAULT": (
        60,
        _("Default cycle period setting of a daemon in seconds"),
        int,
    ),
    "DAEMON_RESTART_TIME_DEFAULT": (
        10,
        _("Default restart time setting of a daemon in seconds"),
        int,
    ),
    "DAEMON_LOG_BACKUP_COUNT_DEFAULT": (
        5,
        _("Default number of daemon logfiles to keep"),
        int,
    ),
    "DAEMON_LOGFILE_SIZE_DEFAULT": (
        1 * 1024 * 1024,
        _("Default maximum size of a daemon logfile in bytes"),
        int,
    ),
    "STORAGE_MAX_FILES_PER_DIR": (
        10000,
        _("Maximum numbers of files in one storage unit."),
        int,
    ),
    "THROW_OUT_SPAM": (
        True,
        _("Whether or not to ignore emails that have a spam flag"),
        bool,
    ),
    "SAVE_CONTENT_TYPE_PREFIXES": (
        ["image", "audio", "video", "model", "font", "application"],
        _(
            "List of content types prefixes to parse as files even if they are not marked as such. For an exhaustive list of all available types see https://www.iana.org/assignments/media-types/media-types.xhtml#text"
        ),
        "array",
    ),
    "DONT_SAVE_CONTENT_TYPE_SUFFIXES": (
        ["plain", "html"],
        _(
            "List of content types prefixes to not parse as files if they are not marked as such. Overrides elements in 'SAVE_CONTENT_TYPE_PREFIXES'."
        ),
        "array",
    ),
    "EMAIL_HTML_TEMPLATE": (
        """{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ email.email_subject }}</title>
    <style>
        {{ email_css }}
    </style>
</head>
<body>
    <div class="email-container">
        <div class="email-header">
            <div class="email-subject">
                {{ email.email_subject }}
            </div>
                <div class="email-datetime">
                {% translate "Received" %}: {{ email.datetime|date:"DATETIME_FORMAT" }}
            </div>
            <div class="email-meta">
                {% for from_emailcorrespondent in from_emailcorrespondents %}
                    {% translate "From" %}: {{ from_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
                {% for to_emailcorrespondent in to_emailcorrespondents %}
                    {% translate "To" %}:{{ to_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
                {% for cc_emailcorrespondent in cc_emailcorrespondents %}
                    {% translate "CC" %}: {{ cc_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
                {% for bcc_emailcorrespondent in bcc_emailcorrespondents %}
                    {% translate "BCC" %}: {{ bcc_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
            </div>
        </div>
        <div class="email-body">
            {% if email.html_bodytext %}
                {{ email.html_bodytext|safe }}
            {% else %}
                <pre>{{ email.plain_bodytext }}</pre>
            {% endif %}
        </div>
        {% if email.attachments.exists %}
        <div class="email-attachments">
            <p><strong>{% translate "Attachments" %}:</strong></p>
            {% for attachment in email.attachments.all %}
                <div class="attachment">
                    {{ attachment.file_name }} {% if attachment.content_id %}(cid: {{ attachment.content_id }}){% endif %}
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</body>
</html>
""",
        _(
            "Html template used to render emails to html. Uses the django template syntax and has access to all fields of the email database table. Removing template tag imports may result in 500 responses when requesting pages with email thumbnails, so be careful."
        ),
        str,
    ),
    "EMAIL_CSS": (
        """body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .email-container {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 20px;
        }
        .email-header {
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .email-subject {
            font-size: 1.5em;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .email-meta,.email-datetime {
            color: #666;
            font-size: 0.9em;
        }
        .email-body {
            margin: 20px 0;
        }
        .email-attachments {
            margin-top: 20px;
        }
        .attachment {
            margin: 5px 0;
        }""",
        _(
            "Css style used to render emails to html. Refer to HTML_TEMPLATE for context on the classes."
        ),
        str,
    ),
    "DEFAULT_SAVE_TO_EML": (
        True,
        _("Default mailbox setting whether to store mails as eml."),
        bool,
    ),
    "DEFAULT_SAVE_ATTACHMENTS": (
        True,
        _("Default mailbox setting whether to store attachments."),
        bool,
    ),
    "REGISTRATION_ENABLED": (
        True,
        _(
            "Set this to True to allow new users to sign up themselves. This setting only takes effect if the REGISTRATION_ENABLED environment setting is not 0."
        ),
        bool,
    ),
}

CONSTANCE_FIELDSETS = (
    (_("Server Configurations"), ("REGISTRATION_ENABLED")),
    (
        _("Default Values"),
        (
            "DEFAULT_SAVE_TO_EML",
            "DEFAULT_SAVE_ATTACHMENTS",
            "DAEMON_CYCLE_PERIOD_DEFAULT",
            "DAEMON_RESTART_TIME_DEFAULT",
            "DAEMON_LOG_BACKUP_COUNT_DEFAULT",
            "DAEMON_LOGFILE_SIZE_DEFAULT",
        ),
    ),
    (
        _("Processing Settings"),
        (
            "THROW_OUT_SPAM",
            "HTML_WRAPPER",
            "SAVE_CONTENT_TYPE_PREFIXES",
            "DONT_SAVE_CONTENT_TYPE_SUFFIXES",
        ),
    ),
    (
        _("Storage Settings"),
        ("STORAGE_MAX_FILES_PER_DIR"),
    ),
    (
        _("API Settings"),
        ("API_DEFAULT_PAGE_SIZE", "API_MAX_PAGE_SIZE"),
    ),
    (
        _("Web Settings"),
        ("WEB_DEFAULT_PAGE_SIZE", "WEB_PAGE_SIZES_OPTIONS"),
    ),
)
