image: python:3.14-slim

default:
  interruptible: true
  before_script:
    - set -o pipefail
    - export DEBIAN_FRONTEND=noninteractive
    - export SECRET_KEY='HELPER_KEY'
    - export PYTHONPATH='src'
    - export DJANGO_SETTINGS_MODULE='config.settings'
    - apt-get update --yes && apt-get install --yes ${APT_DEPENDENCIES} # gitlab-ci-verify: ignore:SC-2086
    - pip install --no-cache poetry

workflow: # when the pipeline should be triggered
  rules: # collect all rules from the jobs here
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "schedule"

variables:
  GITLAB_API_URL: "https://gitlab.com/-/project/$CI_PROJECT_ID"
  GITHUB_API_URL: "https://github.com/-/project/$CI_PROJECT_ID"
  APT_DEPENDENCIES: "build-essential\
    default-mysql-client\
    libmariadb-dev\
    pkg-config"
  CHECK_PATH: "tools/"
  CHECK_CONFIG_PATH: "tools/"
  CHECK_REPORT_PATH: "tools/reports/"
  TEST_PATH: "test/"
  TEST_CONFIG_PATH: "test/"
  TEST_REPORT_PATH: "test/reports/"

stages:
  - test
  - check
  - build

include:
  - local: .gitlab/ci/.gitlab-ci-check-version.yml
  - local: .gitlab/ci/.gitlab-ci-fix_and_format.yml
  - local: .gitlab/ci/.gitlab-ci-lint.yml
  - local: .gitlab/ci/.gitlab-ci-test.yml
  - local: .gitlab/ci/.gitlab-ci-build.yml
  - local: .gitlab/ci/.gitlab-ci-debug-build.yml
  - local: .gitlab/ci/.gitlab-ci-release.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
