version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  apt_packages:
    - python3-dev
    - libkrb5-dev
    - default-mysql-client
  jobs:
    post_install:  # https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-poetry
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
    pre_build:
      - python3 manage.py graph_models -a -g -o docs/source/db_graph.svg
      - python3 manage.py spectacular --validate --file docs/source/api-schema.yml
      - pydeps src/eonvelope --max-bacon 2 -T svg -L ERROR --rankdir LR --no-show --cluster -o docs/source/eonvelope_import_graph.svg
      - pydeps src/core --max-bacon 3 -T svg -L ERROR --rankdir LR --no-show --cluster -o docs/source/core_import_graph.svg
      - pydeps src/api --max-bacon 3 -T svg -L ERROR --rankdir LR --no-show --cluster -o docs/source/api_import_graph.svg
      - pydeps src/web --max-bacon 3 -T svg -L ERROR --rankdir LR --no-show --cluster -o docs/source/web_import_graph.svg

sphinx:
  configuration: docs/source/conf.py
  formats:
  - pdf
  - epub
