#!/command/with-contenv sh
if [ ${ENABLE_FLOWER} = 'True' ]; then
    celery --broker=amqp://guest:guest@localhost:5672// flower
else
    # https://skarnet.org/software/s6/s6-svc.html
	s6-svc -Od .
fi
