# Generated by Django 5.1.4 on 2025-01-25 10:33

import uuid

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Correspondent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_name", models.CharField(blank=True, max_length=255)),
                ("email_address", models.CharField(max_length=255, unique=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "correspondents",
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("directory_number", models.PositiveIntegerField(unique=True)),
                ("path", models.FilePathField(path="/mnt/archive", unique=True)),
                ("subdirectory_count", models.PositiveSmallIntegerField(default=0)),
                ("current", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_address", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("mail_host", models.CharField(max_length=255)),
                ("mail_host_port", models.IntegerField(null=True)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("IMAP", "IMAP"),
                            ("IMAP_SSL", "IMAP_SSL"),
                            ("POP3", "POP3"),
                            ("POP3_SSL", "POP3_SSL"),
                            ("EXCHANGE", "EXCHANGE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timeout", models.IntegerField(null=True)),
                ("is_healthy", models.BooleanField(default=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ConfigurationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DAEMON", "Daemon Config"),
                            ("PARSING", "Parsing Config"),
                            ("STORAGE", "Storage Config"),
                            ("LOGGING", "Logging Config"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                ("value_char", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "config",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "key"),
                        name="configuration_unique_together_category_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailCorrespondent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        choices=[
                            ("From", "FROM"),
                            ("To", "TO"),
                            ("Cc", "CC"),
                            ("Bcc", "BCC"),
                            ("Sender", "SENDER"),
                            ("Reply-To", "REPLY_TO"),
                            ("Resent-From", "RESENT_FROM"),
                            ("Resent-To", "RESENT_TO"),
                            ("Resent-Cc", "RESENT_CC"),
                            ("Resent-Bcc", "RESENT_BCC"),
                            ("Resent-Sender", "RESENT_SENDER"),
                            ("Resent-Reply-To", "RESENT_REPLY_TO"),
                            ("Envelope-To", "ENVELOPE_TO"),
                            ("Delivered-To", "DELIVERED_TO"),
                            ("Return-Path", "RETURN_PATH"),
                            ("Return-Receipt-To", "RETURN_RECEIPT_TO"),
                            (
                                "Disposition-Notification-To",
                                "DISPOSITION_NOTIFICATION_TO",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "correspondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondentemails",
                        to="core.correspondent",
                    ),
                ),
            ],
            options={
                "db_table": "email_correspondents",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255)),
                ("datetime", models.DateTimeField()),
                ("email_subject", models.CharField(max_length=255)),
                ("bodytext", models.TextField()),
                ("datasize", models.IntegerField()),
                (
                    "eml_filepath",
                    models.FilePathField(
                        match=".*\\.eml$",
                        max_length=255,
                        null=True,
                        path="/mnt/archive",
                        recursive=True,
                    ),
                ),
                (
                    "prerender_filepath",
                    models.FilePathField(
                        match=".*\\.jpg$",
                        max_length=255,
                        null=True,
                        path="/mnt/archive",
                        recursive=True,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("comments", models.CharField(max_length=255, null=True)),
                ("keywords", models.CharField(max_length=255, null=True)),
                ("importance", models.CharField(max_length=255, null=True)),
                ("priority", models.CharField(max_length=255, null=True)),
                ("precedence", models.CharField(max_length=255, null=True)),
                ("received", models.TextField(null=True)),
                ("user_agent", models.CharField(max_length=255, null=True)),
                ("auto_submitted", models.CharField(max_length=255, null=True)),
                ("content_type", models.CharField(max_length=255, null=True)),
                ("content_language", models.CharField(max_length=255, null=True)),
                ("content_location", models.CharField(max_length=255, null=True)),
                ("x_priority", models.CharField(max_length=255, null=True)),
                ("x_originated_client", models.CharField(max_length=255, null=True)),
                ("x_spam", models.CharField(max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="core.account",
                    ),
                ),
                (
                    "correspondents",
                    models.ManyToManyField(
                        related_name="emails",
                        through="core.EmailCorrespondent",
                        to="core.correspondent",
                    ),
                ),
                (
                    "inReplyTo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.email",
                    ),
                ),
            ],
            options={
                "db_table": "emails",
            },
        ),
        migrations.AddField(
            model_name="emailcorrespondent",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emailcorrespondents",
                to="core.email",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FilePathField(
                        max_length=511, null=True, path="/mnt/archive", recursive=True
                    ),
                ),
                ("datasize", models.IntegerField()),
                ("is_favorite", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.email",
                    ),
                ),
            ],
            options={
                "db_table": "attachments",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FilePathField(
                        max_length=511, null=True, path="/mnt/archive", recursive=True
                    ),
                ),
                ("datasize", models.IntegerField()),
                ("is_favorite", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.email",
                    ),
                ),
            ],
            options={
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("save_attachments", models.BooleanField(default=True)),
                ("save_images", models.BooleanField(default=True)),
                ("save_toEML", models.BooleanField(default=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_healthy", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to="core.account",
                    ),
                ),
            ],
            options={
                "db_table": "mailboxes",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Daemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "fetching_criterion",
                    models.CharField(
                        choices=[
                            ("RECENT", "RECENT"),
                            ("UNSEEN", "UNSEEN"),
                            ("ALL", "ALL"),
                            ("NEW", "NEW"),
                            ("OLD", "OLD"),
                            ("FLAGGED", "FLAGGED"),
                            ("DRAFT", "DRAFT"),
                            ("ANSWERED", "ANSWERED"),
                            ("DAILY", "DAILY"),
                            ("WEEKLY", "WEEKLY"),
                            ("MONTHLY", "MONTHLY"),
                            ("ANNUALLY", "ANNUALLY"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                ("cycle_interval", models.IntegerField(default=60)),
                ("restart_time", models.IntegerField(default=10)),
                ("is_running", models.BooleanField(default=False)),
                ("is_healthy", models.BooleanField(default=True)),
                ("log_filepath", models.FilePathField(recursive=True, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daemons",
                        to="core.mailbox",
                    ),
                ),
            ],
            options={
                "db_table": "daemons",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_id", models.CharField(max_length=255)),
                ("list_owner", models.CharField(max_length=255, null=True)),
                ("list_subscribe", models.EmailField(max_length=255, null=True)),
                ("list_unsubscribe", models.EmailField(max_length=255, null=True)),
                ("list_post", models.CharField(max_length=255, null=True)),
                ("list_help", models.CharField(max_length=255, null=True)),
                ("list_archive", models.CharField(max_length=255, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "correspondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailinglist",
                        to="core.correspondent",
                    ),
                ),
            ],
            options={
                "db_table": "mailinglists",
            },
        ),
        migrations.AddField(
            model_name="email",
            name="mailinglist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="core.mailinglist",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("mail_address", "user"),
                name="account_unique_together_mail_address_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailcorrespondent",
            constraint=models.UniqueConstraint(
                fields=("email", "correspondent", "mention"),
                name="emailcorrespondents_unique_together_email_correspondent_mention",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.UniqueConstraint(
                fields=("file_path", "email"),
                name="attachment_unique_together_file_path_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                fields=("file_path", "email"),
                name="image_unique_together_file_path_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailbox",
            constraint=models.UniqueConstraint(
                fields=("name", "account"), name="mailbox_unique_together_name_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailinglist",
            constraint=models.UniqueConstraint(
                fields=("list_id", "correspondent"),
                name="mailinglist_unique_together_list_id_correspondent",
            ),
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.UniqueConstraint(
                fields=("message_id", "account"),
                name="email_unique_together_message_id_account",
            ),
        ),
    ]
