# Generated by Django 5.1.4 on 2025-02-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_daemonmodel_log_backup_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmodel",
            name="email_subject",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
