# Generated by Django 5.1.4 on 2025-02-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_emailmodel_email_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmodel",
            old_name="bodytext",
            new_name="plain_bodytext",
        ),
        migrations.AddField(
            model_name="emailmodel",
            name="html_bodytext",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
