# Generated by Django 5.1.6 on 2025-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0007_remove_emailmodel_email_unique_together_message_id_account_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mailinglistmodel",
            name="mailinglist_unique_together_list_id_correspondent",
        ),
        migrations.RemoveField(
            model_name="mailinglistmodel",
            name="correspondent",
        ),
        migrations.AlterField(
            model_name="emailmodel",
            name="prerender_filepath",
            field=models.FilePathField(
                match=".*\\.JPEG$",
                max_length=255,
                null=True,
                path="/mnt/archive",
                recursive=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailinglistmodel",
            name="list_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
