# Generated by Django 5.1.6 on 2025-03-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_accountmodel_protocol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP", "IMAP4"),
                    ("IMAP_SSL", "IMAP4 over SSL"),
                    ("POP3", "POP3"),
                    ("POP3_SSL", "POP3 over SSL"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("RECENT", "RECENT"),
                    ("UNSEEN", "UNSEEN"),
                    ("ALL", "ALL"),
                    ("NEW", "NEW"),
                    ("OLD", "OLD"),
                    ("FLAGGED", "FLAGGED"),
                    ("DRAFT", "DRAFT"),
                    ("ANSWERED", "ANSWERED"),
                    ("DAILY", "Last DAY"),
                    ("WEEKLY", "Last WEEK"),
                    ("MONTHLY", "Last MONTH"),
                    ("ANNUALLY", "Last YEAR"),
                ],
                default="ALL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="mention",
            field=models.CharField(
                choices=[
                    ("From", "From"),
                    ("To", "To"),
                    ("Cc", "CC"),
                    ("Bcc", "BCC"),
                    ("Sender", "Sender"),
                    ("Reply-To", "Reply-To"),
                    ("Resent-From", "Resent-From"),
                    ("Resent-To", "Resent-To"),
                    ("Resent-Cc", "Resent-Cc"),
                    ("Resent-Bcc", "Resent-Bcc"),
                    ("Resent-Sender", "Resent-Sender"),
                    ("Resent-Reply-To", "Resent-Reply-To"),
                    ("Envelope-To", "Envelope-To"),
                    ("Delivered-To", "Delivered-To"),
                    ("Return-Path", "Return-Path"),
                    ("Return-Receipt-To", "Return-Receipt-To"),
                    ("Disposition-Notification-To", "Disposition-Notification-To"),
                ],
                max_length=30,
            ),
        ),
    ]
