# Generated by Django 5.1.7 on 2025-04-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_accountmodel_protocol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailmodel",
            name="prerender_filepath",
        ),
        migrations.AddField(
            model_name="emailmodel",
            name="html_filepath",
            field=models.FilePathField(
                match=".*\\.html$",
                max_length=255,
                null=True,
                path="/mnt/archive",
                recursive=True,
            ),
        ),
        migrations.AddField(
            model_name="mailboxmodel",
            name="save_toHTML",
            field=models.BooleanField(
                default=True,
                help_text="Whether the emails in this mailbox will be converted and stored in .html files.",
                verbose_name="Save as .html",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="mail_address",
            field=models.EmailField(
                help_text="The mail address to the account.",
                max_length=255,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="mail_host",
            field=models.CharField(
                help_text="The URL of the mailserver for the chosen protocol.",
                max_length=255,
                verbose_name="Mailserver-URL",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="mail_host_port",
            field=models.IntegerField(
                blank=True,
                help_text="The port of the mailserver for the chosen protocol.",
                null=True,
                verbose_name="Mailserver-Port",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="password",
            field=models.CharField(max_length=255, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP", "IMAP4"),
                    ("IMAP_SSL", "IMAP4 over SSL"),
                    ("POP3", "POP3"),
                    ("POP3_SSL", "POP3 over SSL"),
                ],
                help_text="The email protocol implemented by the server.",
                max_length=10,
                verbose_name="Email Protocol",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                help_text="Timeout for the connection to the mailserver.",
                null=True,
                verbose_name="Connection Timeout",
            ),
        ),
        migrations.AlterField(
            model_name="correspondentmodel",
            name="email_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The mailer name of the correspondent.",
                max_length=255,
                verbose_name="Mailer name",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="cycle_interval",
            field=models.IntegerField(
                default=60,
                help_text="The time between two daemon runs.",
                verbose_name="Cycle Period",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("RECENT", "RECENT"),
                    ("UNSEEN", "UNSEEN"),
                    ("ALL", "ALL"),
                    ("NEW", "NEW"),
                    ("OLD", "OLD"),
                    ("FLAGGED", "FLAGGED"),
                    ("DRAFT", "DRAFT"),
                    ("ANSWERED", "ANSWERED"),
                    ("DAILY", "Last DAY"),
                    ("WEEKLY", "Last WEEK"),
                    ("MONTHLY", "Last MONTH"),
                    ("ANNUALLY", "Last YEAR"),
                ],
                default="ALL",
                help_text="The selection criterion for emails to archive.",
                max_length=10,
                verbose_name="Fetching Criterion",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="log_backup_count",
            field=models.IntegerField(
                default=5,
                help_text="The number of historical logfiles to keep.",
                verbose_name="Logfile Backup Count",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="logfile_size",
            field=models.IntegerField(
                default=1048576,
                help_text="The maximum size of a logfile in bytes.",
                verbose_name="Logfile Maximum Size",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="restart_time",
            field=models.IntegerField(
                default=10,
                help_text="The time to wait before restarting the daemon after a crash.",
                verbose_name="Restart time",
            ),
        ),
        migrations.AlterField(
            model_name="mailboxmodel",
            name="save_attachments",
            field=models.BooleanField(
                default=True,
                help_text="Whether the attachments from the emails in this mailbox will be saved.",
                verbose_name="Save attachments",
            ),
        ),
        migrations.AlterField(
            model_name="mailboxmodel",
            name="save_toEML",
            field=models.BooleanField(
                default=True,
                help_text="Whether the emails in this mailbox will be stored in .eml files.",
                verbose_name="Save as .eml",
            ),
        ),
    ]
