# Generated by Django 5.2 on 2025-04-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_emailmodel_prerender_filepath_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="mail_host_port",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The port of the mailserver for the chosen protocol.",
                null=True,
                verbose_name="Mailserver-Portnumber",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="password",
            field=models.CharField(
                help_text="The password to the account.",
                max_length=255,
                verbose_name="Password",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="timeout",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Timeout for the connection to the mailserver.",
                null=True,
                verbose_name="Connection Timeout",
            ),
        ),
        migrations.AlterField(
            model_name="attachmentmodel",
            name="datasize",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="cycle_interval",
            field=models.PositiveIntegerField(
                default=60,
                help_text="The time between two daemon runs in seconds.",
                verbose_name="Cycle Period",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="log_backup_count",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="The number of historical logfiles to keep.",
                verbose_name="Logfile Backup Count",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="logfile_size",
            field=models.PositiveIntegerField(
                default=1048576,
                help_text="The maximum size of a logfile in bytes.",
                verbose_name="Logfile Maximum Size",
            ),
        ),
        migrations.AlterField(
            model_name="daemonmodel",
            name="restart_time",
            field=models.PositiveIntegerField(
                default=10,
                help_text="The time to wait before restarting the daemon after a crash in seconds.",
                verbose_name="Restart time",
            ),
        ),
        migrations.AlterField(
            model_name="emailmodel",
            name="datasize",
            field=models.PositiveIntegerField(),
        ),
    ]
