# Generated by Django 5.2.1 on 2025-05-20 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_rename_inreplyto_email_in_reply_to_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="protocol_valid_choice",
        ),
        migrations.AlterField(
            model_name="account",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP", "IMAP4"),
                    ("IMAP4_SSL", "IMAP4 over SSL"),
                    ("POP3", "POP3"),
                    ("POP3_SSL", "POP3 over SSL"),
                ],
                help_text="The email protocol implemented by the server.",
                max_length=10,
                verbose_name="Email Protocol",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("protocol__in", ["IMAP", "IMAP4_SSL", "POP3", "POP3_SSL"])
                ),
                name="protocol_valid_choice",
            ),
        ),
    ]
