# Generated by Django 5.2.1 on 2025-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_storageshard_delete_storage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="message_id",
            field=models.CharField(max_length=255),
        ),
    ]
