# Generated by Django 5.2.1 on 2025-06-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_email_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="in_reply_to",
        ),
        migrations.AddField(
            model_name="email",
            name="in_reply_to",
            field=models.ManyToManyField(related_name="replies", to="core.email"),
        ),
    ]
