# Generated by Django 5.2.1 on 2025-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_daemon_cycle_interval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="mailinglist",
        ),
        migrations.AddField(
            model_name="correspondent",
            name="list_archive",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="list_help",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="list_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="list_owner",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="list_post",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="list_subscribe",
            field=models.EmailField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="list_unsubscribe",
            field=models.EmailField(blank=True, default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="MailingList",
        ),
    ]
