# Generated by Django 5.2.3 on 2025-07-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_correspondent_email_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="emailcorrespondent",
            name="mention_criterion_valid_choice",
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="mention",
            field=models.CharField(
                choices=[
                    ("from", "From"),
                    ("to", "To"),
                    ("cc", "CC"),
                    ("bcc", "BCC"),
                    ("sender", "Sender"),
                    ("reply-To", "Reply-To"),
                    ("resent-from", "Resent-From"),
                    ("resent-to", "Resent-To"),
                    ("resent-cc", "Resent-Cc"),
                    ("resent-bcc", "Resent-Bcc"),
                    ("resent-sender", "Resent-Sender"),
                    ("resent-reply-to", "Resent-Reply-To"),
                    ("envelope-to", "Envelope-To"),
                    ("delivered-to", "Delivered-To"),
                    ("return-path", "Return-Path"),
                    ("return-receipt-to", "Return-Receipt-To"),
                    ("disposition-notification-to", "Disposition-Notification-To"),
                ],
                max_length=30,
                verbose_name="mention",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailcorrespondent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "mention__in",
                        [
                            "from",
                            "to",
                            "cc",
                            "bcc",
                            "sender",
                            "reply-To",
                            "resent-from",
                            "resent-to",
                            "resent-cc",
                            "resent-bcc",
                            "resent-sender",
                            "resent-reply-to",
                            "envelope-to",
                            "delivered-to",
                            "return-path",
                            "return-receipt-to",
                            "disposition-notification-to",
                        ],
                    )
                ),
                name="mention_criterion_valid_choice",
            ),
        ),
    ]
