# Generated by Django 5.2.3 on 2025-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0033_remove_emailcorrespondent_mention_criterion_valid_choice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondent",
            name="list_unsubscribe_post",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="list unsubscribe post",
            ),
        ),
    ]
