# Generated by Django 5.2.4 on 2025-07-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_remove_account_protocol_valid_choice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daemon",
            name="log_filepath",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="logfilepath"
            ),
        ),
    ]
