#!/bin/bash
set -o pipefail

export PYTHONPATH=$PWD'/src/'
export DJANGO_SETTINGS_MODULE='eonvelope.settings'

CONFIG_PATH="tools/"
REPORT_PATH="tools/reports/"


CHANGED_PY_FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.py$')

if [ -z "$CHANGED_PY_FILES" ]; then
  echo "No Python files in commit."
else
  poetry run pylint --rcfile=$CONFIG_PATH'pylintrc_src' $CHANGED_PY_FILES > $REPORT_PATH'pylint_src_precommit.ansi'
  if [ $? -ne 0 ]; then
    echo "Pylinting code failed, please check "$REPORT_PATH"pylint_src_precommit.ansi ."
    exit 1
  fi

  poetry run pylint --rcfile=$CONFIG_PATH'pylintrc_docs' $CHANGED_PY_FILES > $REPORT_PATH'pylint_docs_precommit.ansi'
  if [ $? -ne 0 ]; then
    echo "Pylinting code docs failed, please check "$REPORT_PATH"pylint_docs_precommit.ansi ."
    exit 1
  fi

  poetry run ruff check --config=$CONFIG_PATH'ruff.toml' $CHANGED_PY_FILES > $REPORT_PATH'ruff_precommit.ansi'

  poetry run black --config=$CONFIG_PATH'black_config' $CHANGED_PY_FILES > $REPORT_PATH'black_precommit.ansi'
  if [ $? -ne 0 ]; then
    echo "Formatting code failed, please check "$REPORT_PATH"black_precommit.ansi ."
    exit 1
  fi

  git add $CHANGED_PY_FILES
fi

CHANGED_HTML_FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.html$')

if [ -z "$CHANGED_HTML_FILES" ]; then
  echo "No html files in commit."
else
  poetry run djlint --reformat --configuration $CONFIG_PATH'djlintrc' $CHANGED_HTML_FILES > $REPORT_PATH'djlint_precommit.ansi'
  git add $CHANGED_HTML_FILES

  poetry run djlint --lint --configuration $CONFIG_PATH'djlintrc' $CHANGED_HTML_FILES >> $REPORT_PATH'djlint_precommit.ansi'
  if [ $? -ne 0 ]; then
    echo "Djlint failed, please check "$REPORT_PATH"djlint_precommit.ansi ."
    exit 1
  fi

  poetry run django-admin validate_templates > $REPORT_PATH'validate_templates_precommit.ansi'
  if [ $? -ne 0 ]; then
    echo "Validation of templates failed, please check "$REPORT_PATH"validate_templates_precommit.ansi ."
    exit 1
  fi
fi

CHANGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.js$')
if [ -z "$CHANGED_JS_FILES" ]; then
  echo "No js files in commit."
else
  npx --yes eslint --no-config-lookup --fix
  if [ $? -ne 0 ]; then
    echo "Eslint failed, please check "$REPORT_PATH"eslint_precommit.ansi ."
    exit 1
  fi
fi

CHANGED_RST_FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.rst$')

if [ -z "$CHANGED_RST_FILES" ]; then
  echo "No html files in commit."
else
  poetry run doc8 --config $CONFIG_PATH'doc8.ini' $CHANGED_RST_FILES > $REPORT_PATH'doc8_precommit.ansi'
fi

CHANGED_DOCKERFILE=$(git diff --cached --name-only --diff-filter=ACMRT | grep '^docker/Dockerfile$')
if [ -z "$CHANGED_DOCKERFILE" ]; then
  echo "Dockerfile not in commit."
else
  docker run --rm -i hadolint/hadolint < docker/Dockerfile > $REPORT_PATH'hadolint_precommit.ansi'
fi

poetry run codespell --config=$CONFIG_PATH'.codespellrc' src/ test/ docs/ .gitea/ .github/ .gitlab/ *.md > $REPORT_PATH'codespell_precommit.ansi'

echo "All precommit actions passed successfully."
exit 0
