# Generated by Django 5.1 on 2024-08-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Emailkasten", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_address", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("mail_host", models.CharField(max_length=255)),
                ("mail_host_port", models.IntegerField(null=True)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("IMAP", "IMAP"),
                            ("IMAP_SSL", "IMAP SSL"),
                            ("POP3", "POP3"),
                            ("POP3_SSL", "POP3 SSL"),
                            ("EXCHANGE", "Exchange"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cycle_interval", models.IntegerField(default=60)),
                ("save_attachments", models.BooleanField(default=True)),
                ("save_toEML", models.BooleanField(default=True)),
                ("is_fetched", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="CorrespondentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_name", models.CharField(blank=True, max_length=255)),
                ("email_address", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "db_table": "correspondents",
            },
        ),
        migrations.CreateModel(
            name="EMailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("date_received", models.DateTimeField()),
                ("email_subject", models.CharField(max_length=255)),
                ("bodytext", models.TextField()),
                ("datasize", models.IntegerField()),
                (
                    "eml_filepath",
                    models.FilePathField(
                        match=".*\\.eml$", null=True, path="/mnt/eml/", recursive=True
                    ),
                ),
            ],
            options={
                "db_table": "emails",
            },
        ),
        migrations.CreateModel(
            name="AttachmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FilePathField(
                        null=True, path="/mnt/attachments/", recursive=True, unique=True
                    ),
                ),
                ("datasize", models.IntegerField()),
                (
                    "email_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email",
                        to="Emailkasten.emailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "attachments",
            },
        ),
        migrations.CreateModel(
            name="EMailCorrespondentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        choices=[
                            ("TO", "To"),
                            ("FROM", "From"),
                            ("CC", "Cc"),
                            ("BCC", "Bcc"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "correspondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondents",
                        to="Emailkasten.correspondentmodel",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="Emailkasten.emailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "email_correspondents",
                "unique_together": {("email_id", "correspondent_id", "mention")},
            },
        ),
    ]
