# Generated by Django 5.1 on 2024-08-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachmentmodel",
            old_name="email_id",
            new_name="email",
        ),
        migrations.AlterUniqueTogether(
            name="emailcorrespondentsmodel",
            unique_together={("email", "correspondent", "mention")},
        ),
    ]
