# Generated by Django 5.1 on 2024-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0004_alter_correspondentmodel_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentmodel",
            name="file_path",
            field=models.FilePathField(
                null=True, path="/mnt/archive", recursive=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="emailmodel",
            name="eml_filepath",
            field=models.FilePathField(
                match=".*\\.eml$", null=True, path="/mnt/archive", recursive=True
            ),
        ),
    ]
