# Generated by Django 5.1 on 2024-08-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0005_alter_attachmentmodel_file_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmodel",
            name="eml_filepath",
            field=models.FilePathField(
                match=".*\\.eml$",
                max_length=255,
                null=True,
                path="/mnt/archive",
                recursive=True,
            ),
        ),
    ]
