# Generated by Django 5.1 on 2024-08-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0007_alter_attachmentmodel_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountmodel",
            name="cycle_interval",
        ),
        migrations.RemoveField(
            model_name="accountmodel",
            name="is_fetched",
        ),
        migrations.RemoveField(
            model_name="accountmodel",
            name="save_attachments",
        ),
        migrations.RemoveField(
            model_name="accountmodel",
            name="save_toEML",
        ),
        migrations.CreateModel(
            name="MailboxModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cycle_interval", models.IntegerField(default=60)),
                (
                    "fetching_criterion",
                    models.CharField(
                        choices=[("RECENT", "recent"), ("UNSEEN", "unseen")],
                        default="RECENT",
                        max_length=10,
                    ),
                ),
                ("save_attachments", models.BooleanField(default=True)),
                ("save_toEML", models.BooleanField(default=True)),
                ("is_fetched", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="Emailkasten.accountmodel",
                    ),
                ),
            ],
            options={
                "db_table": "mailboxes",
                "unique_together": {("name", "account")},
            },
        ),
    ]
