# Generated by Django 5.1 on 2024-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emailkasten", "0008_remove_accountmodel_cycle_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailboxmodel",
            name="fetching_criterion",
            field=models.CharField(
                choices=[("RECENT", "recent"), ("UNSEEN", "unseen"), ("ALL", "all")],
                default="RECENT",
                max_length=10,
            ),
        ),
    ]
