# Generated by Django 5.1 on 2024-08-22 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0011_accountmodel_is_healthy_accountmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Emailkasten.emailmodel'),
        ),
        migrations.AlterField(
            model_name='emailcorrespondentsmodel',
            name='correspondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailcorrespondents', to='Emailkasten.correspondentmodel'),
        ),
        migrations.AlterField(
            model_name='emailcorrespondentsmodel',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondentemails', to='Emailkasten.emailmodel'),
        ),
        migrations.AlterField(
            model_name='mailboxmodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='Emailkasten.accountmodel'),
        ),
    ]
