# Generated by Django 5.1 on 2024-08-22 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0012_alter_accountmodel_user_alter_attachmentmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcorrespondentsmodel',
            name='correspondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondentemails', to='Emailkasten.correspondentmodel'),
        ),
        migrations.AlterField(
            model_name='emailcorrespondentsmodel',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailcorrespondents', to='Emailkasten.emailmodel'),
        ),
    ]
