# Generated by Django 5.1.1 on 2024-10-05 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0022_mailinglistmodel_emailmodel_auto_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglistmodel',
            name='correspondent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mailinglist', to='Emailkasten.correspondentmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailinglistmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailinglistmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
