# Generated by Django 5.1.1 on 2024-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0023_mailinglistmodel_correspondent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='received',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
