# Generated by Django 5.1.1 on 2024-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0025_alter_emailmodel_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='delivered_to',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='disposition_notification_to',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='envelope_to',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='return_path',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='return_receipt_to',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='sender',
        ),
        migrations.AlterField(
            model_name='emailcorrespondentsmodel',
            name='mention',
            field=models.CharField(choices=[('FROM', 'From'), ('TO', 'To'), ('BCC', 'Bcc'), ('CC', 'Cc'), ('REPLY_TO', 'Reply-To'), ('RETURN_PATH', 'Return-Path'), ('ENVELOPE_TO', 'Envelope-To'), ('DELIVERED_TO', 'Delivered-To'), ('SENDER', 'Sender'), ('RETURN_RECEIPT_TO', 'Return-Receipt-To'), ('DISPOSITION_NOTIFICATION_TO', 'Disposition-Notification-To')], max_length=30),
        ),
    ]
