# Generated by Django 5.1.2 on 2024-10-17 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0027_storagemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondentmodel',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='correspondents', to='Emailkasten.accountmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='mail_address',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='file_path',
            field=models.FilePathField(max_length=511, null=True, path='/mnt/archive', recursive=True),
        ),
        migrations.AlterField(
            model_name='correspondentmodel',
            name='email_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='message_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='file_path',
            field=models.FilePathField(max_length=511, null=True, path='/mnt/archive', recursive=True),
        ),
        migrations.AlterField(
            model_name='mailboxmodel',
            name='fetching_criterion',
            field=models.CharField(choices=[('RECENT', 'RECENT'), ('UNSEEN', 'UNSEEN'), ('ALL', 'ALL'), ('NEW', 'NEW'), ('OLD', 'OLD'), ('FLAGGED', 'FLAGGED'), ('ANSWERED', 'ANSWERED'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('ANNUALLY', 'ANNUALLY')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='mailinglistmodel',
            name='list_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='accountmodel',
            unique_together={('mail_address', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='attachmentmodel',
            unique_together={('file_path', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='correspondentmodel',
            unique_together={('email_address', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='emailmodel',
            unique_together={('message_id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='imagemodel',
            unique_together={('file_path', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='mailinglistmodel',
            unique_together={('list_id', 'correspondent')},
        ),
    ]
