# Generated by Django 5.1.1 on 2024-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0029_accountmodel_is_favorite_attachmentmodel_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correspondentmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='correspondentmodel',
            name='email_address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='correspondentmodel',
            name='account',
        ),
    ]
