# Generated by Django 5.1 on 2024-11-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0033_daemonmodel_is_healthy'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='timeout',
            field=models.IntegerField(null=True),
        ),
    ]
