# Generated by Django 5.1 on 2024-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0034_accountmodel_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemonmodel',
            name='log_filepath',
            field=models.FilePathField(null=True, recursive=True, unique=True),
        ),
    ]
