# Generated by Django 5.1 on 2024-11-25 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0035_alter_daemonmodel_log_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailboxmodel',
            name='fetching_criterion',
        ),
        migrations.AddField(
            model_name='daemonmodel',
            name='fetching_criterion',
            field=models.CharField(choices=[('RECENT', 'RECENT'), ('UNSEEN', 'UNSEEN'), ('ALL', 'ALL'), ('NEW', 'NEW'), ('OLD', 'OLD'), ('FLAGGED', 'FLAGGED'), ('DRAFT', 'DRAFT'), ('ANSWERED', 'ANSWERED'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('ANNUALLY', 'ANNUALLY')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='daemonmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='daemonmodel',
            name='log_filepath',
            field=models.FilePathField(default=0, recursive=True, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daemonmodel',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daemons', to='Emailkasten.mailboxmodel'),
        ),
    ]
