# Generated by Django 5.1.4 on 2025-01-09 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailkasten', '0036_remove_mailboxmodel_fetching_criterion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='configurationmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='emailcorrespondentsmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='emailmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='imagemodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mailboxmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mailinglistmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='protocol',
            field=models.CharField(choices=[('IMAP', 'IMAP'), ('IMAP_SSL', 'IMAP_SSL'), ('POP3', 'POP3'), ('POP3_SSL', 'POP3_SSL'), ('EXCHANGE', 'EXCHANGE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emailcorrespondentsmodel',
            name='mention',
            field=models.CharField(choices=[('From', 'FROM'), ('To', 'TO'), ('Cc', 'CC'), ('Bcc', 'BCC'), ('Sender', 'SENDER'), ('Reply-To', 'REPLY_TO'), ('Resent-From', 'RESENT_FROM'), ('Resent-To', 'RESENT_TO'), ('Resent-Cc', 'RESENT_CC'), ('Resent-Bcc', 'RESENT_BCC'), ('Resent-Sender', 'RESENT_SENDER'), ('Resent-Reply-To', 'RESENT_REPLY_TO'), ('Envelope-To', 'ENVELOPE_TO'), ('Delivered-To', 'DELIVERED_TO'), ('Return-Path', 'RETURN_PATH'), ('Return-Receipt-To', 'RETURN_RECEIPT_TO'), ('Disposition-Notification-To', 'DISPOSITION_NOTIFICATION_TO')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='accountmodel',
            constraint=models.UniqueConstraint(fields=('mail_address', 'user'), name='account_unique_together_mail_address_user'),
        ),
        migrations.AddConstraint(
            model_name='attachmentmodel',
            constraint=models.UniqueConstraint(fields=('file_path', 'email'), name='attachment_unique_together_file_path_email'),
        ),
        migrations.AddConstraint(
            model_name='configurationmodel',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='configuration_unique_together_category_key'),
        ),
        migrations.AddConstraint(
            model_name='emailcorrespondentsmodel',
            constraint=models.UniqueConstraint(fields=('email', 'correspondent', 'mention'), name='emailcorrespondents_unique_together_email_correspondent_mention'),
        ),
        migrations.AddConstraint(
            model_name='emailmodel',
            constraint=models.UniqueConstraint(fields=('message_id', 'account'), name='email_unique_together_message_id_account'),
        ),
        migrations.AddConstraint(
            model_name='imagemodel',
            constraint=models.UniqueConstraint(fields=('file_path', 'email'), name='image_unique_together_file_path_email'),
        ),
        migrations.AddConstraint(
            model_name='mailboxmodel',
            constraint=models.UniqueConstraint(fields=('name', 'account'), name='mailbox_unique_together_name_account'),
        ),
        migrations.AddConstraint(
            model_name='mailinglistmodel',
            constraint=models.UniqueConstraint(fields=('list_id', 'correspondent'), name='mailinglist_unique_together_list_id_correspondent'),
        ),
    ]
