# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Emailkasten - a open-source self-hostable email archiving server
# Copyright (C) 2024  David & Philipp Aderbauer
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
"""
Django settings for Emailkasten project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

import api.constants
import Emailkasten.constants


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-854!q(ej3aqf0agllzt^#u$=aqe33xd1zj*vz^$xi1tmw^bxn5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "rest_framework",
    'rest_framework.authtoken',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    'django.contrib.sites',
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_filters",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "constance",
    "constance.backends.database",
    "health_check",
    "health_check.db",
    "health_check.storage",
    "health_check.cache",
    "Emailkasten",
    "core",
    "api"
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'api.v1.pagination.Pagination',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES' : [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

MIDDLEWARE = [
    "core.middleware.DBReconnectMiddleware.DBReconnectMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "Emailkasten.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Emailkasten.wsgi.application"

SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": Emailkasten.constants.DatabaseConfiguration.NAME,
        "USER": Emailkasten.constants.DatabaseConfiguration.USER,
        "PASSWORD": Emailkasten.constants.DatabaseConfiguration.PASSWORD,
        "HOST": "db",
        "PORT": '3306',
        "OPTIONS": {
             'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'none'
REGISTRATION_ENABLED = api.constants.APIv1Configuration.REGISTRATION_ENABLED
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

REST_USE_JWT = False
REST_AUTH_TOKEN_MODEL = 'rest_framework.authtoken.models.Token'

SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False
#SESSION_COOKIE_SECURE = True

CSRF_COOKIE_AGE = 31449600
#CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False


# logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        "default": {
            'format': Emailkasten.constants.LoggerConfiguration.LOG_FORMAT,
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
        'django_logfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(
                Emailkasten.constants.LoggerConfiguration.LOG_DIRECTORY_PATH,
                Emailkasten.constants.LoggerConfiguration.DJANGO_LOGFILE_NAME
            ),
            'maxBytes': Emailkasten.constants.LoggerConfiguration.LOGFILE_MAXSIZE,
            'backupCount': Emailkasten.constants.LoggerConfiguration.LOGFILE_BACKUP_NUMBER,
            'formatter': 'default',
        },
        'app_logfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(
                Emailkasten.constants.LoggerConfiguration.LOG_DIRECTORY_PATH,
                Emailkasten.constants.LoggerConfiguration.APP_LOGFILE_NAME
            ),
            'maxBytes': Emailkasten.constants.LoggerConfiguration.LOGFILE_MAXSIZE,
            'backupCount': Emailkasten.constants.LoggerConfiguration.LOGFILE_BACKUP_NUMBER,
            'formatter': 'default',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': Emailkasten.constants.LoggerConfiguration.ROOT_LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['django_logfile'],
            'level': Emailkasten.constants.LoggerConfiguration.DJANGO_LOG_LEVEL,
            'propagate': True,
        },
        "Emailkasten": {
            'handlers': ['app_logfile'],
            'level': Emailkasten.constants.LoggerConfiguration.APP_LOG_LEVEL,
            'propagate': True,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_URL = [
    os.path.join( BASE_DIR, 'static' ),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Constance settings

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True

CONSTANCE_CONFIG = {
    'API_DEFAULT_PAGE_SIZE': (20, _('The default page size for paginated API response data'), int),
    'API_MAX_PAGE_SIZE': (200, _('The maximum page size for paginated API response data'), int),
    'DAEMON_CYCLE_PERIOD_DEFAULT': (60, _('The default cycle period setting of a daemon in seconds'), int),
    'DAEMON_RESTART_TIME_DEFAULT': (10, _('The default restart time setting of a daemon in seconds'), int),
    'STORAGE_MAX_SUBDIRS_PER_DIR': (1000, _('The maximum numbers of subdirectories in one storage unit. Must not exceed 64000 for ext4 filesystem!'), int),
    'STORAGE_PATH': ('/mnt/archive', _('The path to the storage for the saved data. Must match the path in the docker-compose.yml to ensure data persistence!'), str),
    'PRERENDER_IMAGETYPE': ('jpg', _('The image format for the prerendered eml files'), str),
    'DEFAULT_CHARSET': ('utf-8', _('The default charset used for decoding of text'), str),
    'STRIP_TEXTS': (True, _('Whether or not to strip whitespace from textfields like bodytext and subject'), bool),
    'THROW_OUT_SPAM': (True, _('Whether or not to ignore emails that have a spam flag'), bool),
    'DEFAULT_MAILDATE': ('1971-01-01 00:00:00', _('The fallback date to use if none is found in a mail'), str),
    'TEMPORARY_STORAGE_DIRECTORY': ('/tmp/images', _('The path where intermediate images of the prerendering process will be placed'), str),
    'HTML_WRAPPER': (
        """<html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    font-size: 14px;
                    white-space: pre-wrap;
                }}
            </style>
        </head>
        <body>
            <pre>%s</pre>
        </body>
        </html>""",
        'The html template to wrap around plain text before prerendering',
        str
    ),
    'DEFAULT_SAVE_TO_EML': (True, _('The default mailbox setting whether to store mails as eml'), bool),
    'DEFAULT_SAVE_ATTACHMENTS': (True, _('The default mailbox setting whether to store attachments'), bool),
    'DEFAULT_SAVE_IMAGES': (True, _('The default mailbox setting whether to store images'), bool),
}

CONSTANCE_FIELDSETS = (
    (
        _('Default Values'),
        (
            'DEFAULT_SAVE_TO_EML',
            'DEFAULT_SAVE_ATTACHMENTS',
            'DEFAULT_SAVE_IMAGES',
            'DEFAULT_MAILDATE',
            'DAEMON_CYCLE_PERIOD_DEFAULT',
            'DAEMON_RESTART_TIME_DEFAULT',
        )
    ),
    (
        _('Processing Settings'),
        (
            'THROW_OUT_SPAM',
            'STRIP_TEXTS',
            'HTML_WRAPPER',
            'PRERENDER_IMAGETYPE',
            'DEFAULT_CHARSET'
        )
    ),
    (
        _('Storage Settings'),
        (
            'STORAGE_PATH',
            'STORAGE_MAX_SUBDIRS_PER_DIR',
            'TEMPORARY_STORAGE_DIRECTORY'
        )
    ),
    (
        _('API Settings'),
        (
            'API_DEFAULT_PAGE_SIZE',
            'API_MAX_PAGE_SIZE'
        )
    )
)
