# Generated by Django 5.2.6 on 2025-09-19 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eonvelope", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="immich_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="API key for your Immich server.",
                max_length=255,
                verbose_name="Immich server API key",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="immich_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of your Immich server.",
                max_length=255,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
                verbose_name="Immich server URL",
            ),
        ),
    ]
