# Generated by Django 5.2.6 on 2025-09-20 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eonvelope", "0002_userprofile_immich_api_key_userprofile_immich_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nextcloud_addressbook",
            field=models.CharField(
                blank=True,
                default="contacts",
                help_text="Main addressbook of your Nextcloud account.",
                max_length=255,
                verbose_name="Nextcloud server addressbook",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nextcloud_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Password for your Nextcloud account.",
                max_length=255,
                verbose_name="Nextcloud server API key",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nextcloud_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of your Nextcloud server.",
                max_length=255,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
                verbose_name="Nextcloud server URL",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nextcloud_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Username for your Nextcloud account.",
                max_length=255,
                verbose_name="Nextcloud server username",
            ),
        ),
    ]
