# Generated by Django 5.2.6 on 2025-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eonvelope", "0003_userprofile_nextcloud_addressbook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nextcloud_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Password for your Nextcloud account.",
                max_length=255,
                verbose_name="Nextcloud server password",
            ),
        ),
    ]
