# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Eonvelope - a open-source self-hostable email archiving server
# Copyright (C) 2024 David Aderbauer & The Eonvelope Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
"""Django settings for Eonvelope project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from __future__ import annotations

import re
import socket
import sys
from pathlib import Path

import tomli
from django.utils.translation import get_language, get_language_bidi, get_language_info
from django.utils.translation import gettext_lazy as _
from environ import FileAwareEnv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(BASE_DIR / "src"))

# Get environ either from environment and file defined via _FILE env-variable
# See https://django-environ.readthedocs.io/en/latest/tips.html#docker-style-file-based-variables
env = FileAwareEnv()
env.read_env(BASE_DIR / ".env")

# Version synced from pyproject config file
with open(BASE_DIR / "pyproject.toml", "rb") as f:
    config = tomli.load(f)
VERSION = config["project"]["version"]


# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/ for safe settings


##### django core #####
# https://docs.djangoproject.com/en/5.2/ref/settings/#core-settings

### Models

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.humanize",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pwa",
    "django_extensions",
    "django_prometheus",
    "debug_toolbar",
    "import_export",
    "schema_viewer",
    "django_filters",
    "django_tables2",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.mfa",
    "allauth.headless",
    "allauth.socialaccount",
    "allauth.usersessions",
    "robots",
    "constance",
    "constance.backends.database",
    "health_check",
    "health_check.db",
    "health_check.storage",
    "health_check.cache",
    "django_bootstrap5",
    "crispy_forms",
    "crispy_bootstrap5",
    "fontawesomefree",
    "health_check.contrib.migrations",
    "health_check.contrib.psutil",
    "health_check.contrib.rabbitmq",
    "health_check.contrib.celery_ping",
    "django_celery_results",
    "django_celery_beat",
    "eonvelope",
    "core",
    "api",
    "web",
]


### Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": (
            "django_prometheus.db.backends." + env("DATABASE_TYPE", default="mysql")
        ),
        "NAME": env("DATABASE", default="email_archive_django"),
        "USER": env("DATABASE_USER", default="user"),
        "PASSWORD": env("DATABASE_PASSWORD", default="passwd"),
        "HOST": "db",
        "OPTIONS": (
            {
                "charset": "utf8mb4",
            }
            if env("DATABASE_TYPE", default="mysql") == "mysql"
            else {}
        ),
    }
}

CONN_MAX_AGE = 3600
CONN_HEALTH_CHECKS = True

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

### Cache
# https://docs.djangoproject.com/en/5.1/ref/settings/#cache

CACHES = {
    "default": {
        "BACKEND": "django_prometheus.cache.backends.locmem.LocMemCache",
    }
}
CACHE_MIDDLEWARE_SECONDS = env("CACHE_MIDDLEWARE_SECONDS", cast=int, default=600)


### Storage
# https://docs.djangoproject.com/en/5.2/ref/settings/#storages

STORAGE_PATH = "/mnt/archive"

STORAGES = {
    "default": {
        "BACKEND": "core.backends.ShardedFileSystemStorage.ShardedFileSystemStorage",
        "OPTIONS": {
            "location": STORAGE_PATH,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


### Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/

LOG_DIRECTORY_PATH = Path(env("LOG_DIRECTORY_PATH", default="/var/log/eonvelope"))

LOGFILE_MAXSIZE = env("LOGFILE_MAXSIZE", cast=int, default=10485760)

LOGFILE_BACKUP_NUMBER = env("LOGFILE_BACKUP_NUMBER", cast=int, default=5)

LOGLEVEL_DEFAULT = "INFO"

LOGFORMAT = "{asctime} {levelname} - {name}.{funcName}: {message}"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": LOGFORMAT,
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
        "django_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "django.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "celery_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "celery.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "amqp_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "amqp.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "eonvelope_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "eonvelope.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "core_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "core.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "api_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "api.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
        "web_logfile": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIRECTORY_PATH / "web.log",
            "maxBytes": LOGFILE_MAXSIZE,
            "backupCount": LOGFILE_BACKUP_NUMBER,
            "formatter": "default",
        },
    },
    "root": {
        "handlers": ["console", "eonvelope_logfile"],
        "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
    },
    "loggers": {
        "django": {
            "handlers": ["console", "django_logfile"],
            "level": env("DJANGO_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": False,
        },
        "celery": {
            "handlers": ["console", "celery_logfile"],
            "level": env("CELERY_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": False,
        },
        "amqp": {
            "handlers": ["console", "amqp_logfile"],
            "level": env("AMQP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": False,
        },
        "core": {
            "handlers": ["core_logfile"],
            "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": True,
        },
        "api": {
            "handlers": ["api_logfile"],
            "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": True,
        },
        "web": {
            "handlers": ["web_logfile"],
            "level": env("APP_LOG_LEVEL", default=LOGLEVEL_DEFAULT),
            "propagate": True,
        },
    },
}


### Debug

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", cast=bool, default=False)


### Globalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Internationalization
# https://docs.djangoproject.com/en/5.2/ref/settings/#globalization-i18n-l10n
USE_I18N = True

LANGUAGE_CODES = [
    "ar",
    "az",
    "bg",
    "ca",
    "cs",
    "da",
    "de",
    "el",
    "en",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fr",
    "he",
    "hr",
    "hu",
    "id",
    "it",
    "ja",
    "ka",
    "ko",
    "ky",
    "lt",
    "lv",
    "mn",
    "nb",
    "nl",
    "pl",
    "pt-BR",
    "pt-PT",
    "ro",
    "ru",
    "sk",
    "sl",
    "sr",
    "sr",
    "sv",
    "th",
    "tr",
    "uk",
    "zh-hans",
    "zh-hant",
]
LANGUAGES = [
    (language, get_language_info(language)["name_local"]) for language in LANGUAGE_CODES
]

LOCALE_PATHS = [
    BASE_DIR / "src" / "eonvelope" / "locale",
    BASE_DIR / "src" / "core" / "locale",
    BASE_DIR / "src" / "api" / "locale",
    BASE_DIR / "src" / "web" / "locale",
]

DEFAULT_COOKIE_AGE = 2419200  # 4 weeks

LANGUAGE_COOKIE_AGE = env("LANGUAGE_COOKIE_AGE", cast=int, default=DEFAULT_COOKIE_AGE)
LANGUAGE_COOKIE_SECURE = not DEBUG
LANGUAGE_COOKIE_SAMESITE = env("LANGUAGE_COOKIE_SAMESITE", cast=str, default=None)


# Timezones
# https://docs.djangoproject.com/en/5.2/topics/i18n/timezones/
USE_TZ = True

TIME_ZONE = "UTC"  # changing this doesn't change the celery schedule https://django-celery-beat.readthedocs.io/en/latest/#important-warning-about-time-zones

# Localization
# https://docs.djangoproject.com/en/5.2/ref/settings/#localization-l10n
USE_L10N = True

LANGUAGE_CODE = "en"


### HTTP
# https://docs.djangoproject.com/en/5.2/ref/settings/#http

WSGI_APPLICATION = "eonvelope.wsgi.application"

# https://knasmueller.net/fix-djangos-debug-toolbar-not-showing-inside-docker
hostname, __, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [".".join([*ip.split(".")[:-1], "1"]) for ip in ips]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "allauth.usersessions.middleware.UserSessionsMiddleware",
    "eonvelope.middleware.TimezoneMiddleware.TimezoneMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

# Security
ALLOWED_HOSTS = env("ALLOWED_HOSTS", cast=list, default=["localhost", "127.0.0.1"])
if "localhost" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("localhost")
if "127.0.0.1" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("127.0.0.1")
if (
    "0.0.0.0"  # noqa: S104 ; allow access from inside the docker container
    not in ALLOWED_HOSTS
    and DEBUG
):
    ALLOWED_HOSTS.append(
        "0.0.0.0"  # noqa: S104 ; allow access from inside the docker container
    )

DISALLOWED_USER_AGENTS = [
    re.compile(pattern)
    for pattern in env("DISALLOWED_USER_AGENTS", cast=list, default=[])
]

SECURE_HSTS_SECONDS = (
    0 if DEBUG else env("SECURE_HSTS_SECONDS", cast=int, default=31536000)
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

SECURE_SSL_REDIRECT = not DEBUG


### URLs
# https://docs.djangoproject.com/en/5.2/ref/settings/#urls

ROOT_URLCONF = "eonvelope.urls"


### Templates
# https://docs.djangoproject.com/en/5.2/ref/settings/#id11

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "src" / "eonvelope" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "constance.context_processors.config",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django_settings_export.settings_export",
            ],
        },
    },
]


### Security
# https://docs.djangoproject.com/en/5.2/ref/settings/#security

# CSRF
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_AGE = env("CSRF_COOKIE_AGE", cast=int, default=31449600)
CSRF_COOKIE_HTTPONLY = False  # to allow Cookie.js to access the cookie
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS", cast=list, default=[])
CSRF_COOKIE_SAMESITE = env("CSRF_COOKIE_SAMESITE", cast=str, default="Lax")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


### File uploads
# https://docs.djangoproject.com/en/5.2/ref/settings/#file-uploads

FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]


##### django.contrib.auth #####
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

STRICT_PASSWORDS_DEFAULT = True
AUTH_PASSWORD_VALIDATORS = (
    [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]
    if env("STRICT_PASSWORDS", cast=bool, default=STRICT_PASSWORDS_DEFAULT)
    else []
)

LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "web:dashboard"
LOGOUT_REDIRECT_URL = "account_login"

# Custom Registration
REGISTRATION_ENABLED_DEFAULT = False
REGISTRATION_ENABLED = env(
    "REGISTRATION_ENABLED", cast=bool, default=REGISTRATION_ENABLED_DEFAULT
)


##### django.contrib.sessions #####
# https://docs.djangoproject.com/en/5.2/ref/settings/#sessions

SESSION_COOKIE_AGE = env("SESSION_COOKIE_AGE", cast=int, default=DEFAULT_COOKIE_AGE)
SESSION_EXPIRE_AT_BROWSER_CLOSE = env(
    "SESSION_EXPIRE_AT_BROWSER_CLOSE", cast=bool, default=False
)
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", cast=str, default="Lax")


##### django.contrib.sites #####
# https://docs.djangoproject.com/en/5.2/ref/settings/#sites

SITE_ID = 1


##### django.contrib.staticfiles #####
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# https://docs.djangoproject.com/en/5.2/ref/settings/#static-files

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


##### django-pwa #####
# https://pypi.org/project/django-pwa/

PWA_APP_NAME = "Eonvelope"
PWA_APP_DESCRIPTION = _("Your email archiving server")
PWA_APP_THEME_COLOR = "#0d6efd"
PWA_APP_BACKGROUND_COLOR = "#ffffff"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_ORIENTATION = "any"
PWA_APP_START_URL = "/dashboard/"
PWA_APP_STATUS_BAR_COLOR = "default"
PWA_APP_ICONS = [
    {
        "src": STATIC_URL + "eonvelope/icons/favicon-512x512.png",
        "sizes": "512x512",
        "type": "image/png",
        "purpose": "maskable",
    },
    {
        "src": STATIC_URL + "eonvelope/icons/favicon-192x192.png",
        "sizes": "192x192",
        "type": "image/png",
        "purpose": "maskable",
    },
]
PWA_APP_ICONS_APPLE = [
    {
        "src": STATIC_URL + "eonvelope/icons/apple-touch-icon.png",
        "sizes": "180x180",
        "type": "image/png",
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        "src": STATIC_URL + "eonvelope/icons/favicon-512x512.png",
        "sizes": "512x512",
        "type": "image/png",
        "purpose": "maskable",
        "media": "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)",
    },
]
PWA_APP_DIR = "rtl" if get_language_bidi() else "ltr"
PWA_APP_LANG = get_language()
PWA_APP_SHORTCUTS = [
    {
        "name": _("Dashboard"),
        "url": "/dashboard/",
        "description": _("Shortcut to the dashboard"),
    },
    {
        "name": _("Timeline"),
        "url": "/emails/archive/",
        "description": _("Shortcut to the email timeline"),
    },
]
PWA_APP_SCREENSHOTS = []
PWA_APP_DEBUG_MODE = DEBUG


##### django-debug-toolbar #####
# https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": "debug_toolbar.middleware.show_toolbar_with_docker",
}

##### django-settings-export #####
# https://github.com/jkbrzt/django-settings-export/blob/master/README.md
# !! package is quite old but very small; it may break at some point !!

SETTINGS_EXPORT = [
    "DEBUG",
    "VERSION",
]


##### django_prometheus ######
# https://github.com/django-commons/django-prometheus/blob/master/README.md

PROMETHEUS_METRIC_NAMESPACE = "eonvelope"


##### restframework #####
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "api.v1.pagination.Pagination",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "allauth.headless.contrib.rest_framework.authentication.XSessionTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "eonvelope.auth.BasicNoMFAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}

##### celery #####
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html#using-celery-with-django

CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672//"
BROKER_URL = CELERY_BROKER_URL  # required for rabbitmq django-healthcheck


##### allauth #####
# https://django-allauth.readthedocs.io/en/latest/index.html

# account
ACCOUNT_ADAPTER = "eonvelope.utils.toggle_signup.ToggleSignupAccountAdapter"
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_LOGIN_TIMEOUT = env("ACCOUNT_LOGIN_TIMEOUT", cast=int, default=900)
ACCOUNT_SIGNUP_FIELDS = ["username*", "password1*", "password2*"]
ACCOUNT_USERNAME_BLACKLIST = env("ACCOUNT_USERNAME_BLACKLIST", cast=list, default=[])
ACCOUNT_USERNAME_MIN_LENGTH = env("ACCOUNT_USERNAME_MIN_LENGTH", cast=int, default=1)
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_SESSION_REMEMBER = env("ACCOUNT_SESSION_REMEMBER", cast=bool, default=None)
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = env(
    "ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE", cast=bool, default=False
)
ACCOUNT_REAUTHENTICATION_TIMEOUT = env(
    "ACCOUNT_REAUTHENTICATION_TIMEOUT", cast=int, default=300
)
ACCOUNT_REAUTHENTICATION_REQUIRED = env(
    "ACCOUNT_REAUTHENTICATION_REQUIRED", cast=bool, default=False
)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https" if not DEBUG else "http"
ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = "phone"

# usersessions
USERSESSIONS_TRACK_ACTIVITY = env("USERSESSIONS_KEEP_UPDATED", cast=bool, default=True)

# headless
HEADLESS_ONLY = False
HEADLESS_SERVE_SPECIFICATION = True

# mfa
MFA_ALLOW_UNVERIFIED_EMAIL = True

MFA_TOTP_ISSUER = env("MFA_TOTP_ISSUER", cast=str, default="Eonvelope")
MFA_TOTP_PERIOD = env("MFA_TOTP_PERIOD", cast=int, default=30)
MFA_TOTP_DIGITS = env("MFA_TOTP_DIGITS", cast=int, default=6)
MFA_TOTP_TOLERANCE = env("MFA_TOTP_TOLERANCE", cast=int, default=1)

MFA_RECOVERY_CODE_COUNT = env("MFA_RECOVERY_CODE_COUNT", cast=int, default=10)
MFA_RECOVERY_CODE_DIGITS = env("MFA_RECOVERY_CODE_DIGITS", cast=int, default=8)

MFA_TRUST_ENABLED = env("MFA_TRUST_ENABLED", cast=bool, default=True)
MFA_TRUST_COOKIE_AGE = env("MFA_TRUST_COOKIE_AGE", cast=int, default=DEFAULT_COOKIE_AGE)
MFA_TRUST_COOKIE_SECURE = not DEBUG
MFA_TRUST_COOKIE_SAMESITE = env("MFA_TRUST_COOKIE_SAMESITE", cast=str, default="Lax")


##### crispy_forms #####
# https://django-crispy-forms.readthedocs.io/en/latest/index.html

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_FAIL_SILENTLY = not DEBUG


##### django-bootstrap5 #####
# https://django-bootstrap5.readthedocs.io/en/latest/settings.html

BOOTSTRAP5 = {"css_url": STATIC_URL + "eonvelope/css/eonvelope.css"}


##### django_tables2 #####
# https://django-tables2.readthedocs.io/en/latest/pages/custom-rendering.html

DJANGO_TABLES2_TEMPLATE = "web/partials/_table.html"
DJANGO_TABLES2_TABLE_ATTRS = {
    "class": "table table-hover table-striped-columns align-middle",
    "tbody": {"class": "table-group-divider"},
    "tfoot": {"class": "table-group-divider"},
}


##### drf_spectacular #####
# https://drf-spectacular.readthedocs.io/en/latest/settings.html#settings

SPECTACULAR_SETTINGS = {
    "TITLE": "Eonvelope API",
    "DESCRIPTION": "The API schema for the Eonvelope server.",
    "VERSION": VERSION,
    "SERVE_INCLUDE_SCHEMA": True,
}


##### robots #####
# https://django-robots.readthedocs.io/en/latest/

ROBOTS_USE_SITEMAP = False
ROBOTS_USE_HOST = False


##### constance #####
# https://django-constance.readthedocs.io/en/latest/#configuration

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True

# Solution to have collection types, see https://github.com/jazzband/django-constance/issues/620
CONSTANCE_ADDITIONAL_FIELDS = {
    list: ["django.forms.fields.JSONField", {"widget": "django.forms.Textarea"}],
    dict: ["django.forms.fields.JSONField", {"widget": "django.forms.Textarea"}],
    "text": ["django.forms.fields.CharField", {"widget": "django.forms.Textarea"}],
}

# Defaults
EMAIL_HTML_TEMPLATE_DEFAULT = """{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ email.subject }}</title>
    <style>
        {{ email_css }}
    </style>
</head>
<body>
    <div class="email-container">
        <div class="email-header">
            <div class="email-subject">
                {{ email.subject }}
            </div>
                <div class="email-datetime">
                {% translate "Received" %}: {{ email.datetime|date:"DATETIME_FORMAT" }}
            </div>
            <div class="email-meta">
                {% for from_emailcorrespondent in from_emailcorrespondents %}
                    {% translate "From" %}: {{ from_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
                {% for to_emailcorrespondent in to_emailcorrespondents %}
                    {% translate "To" %}:{{ to_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
                {% for cc_emailcorrespondent in cc_emailcorrespondents %}
                    {% translate "CC" %}: {{ cc_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
                {% for bcc_emailcorrespondent in bcc_emailcorrespondents %}
                    {% translate "BCC" %}: {{ bcc_emailcorrespondent.correspondent.email_address }}<br>
                {% endfor %}
            </div>
        </div>
        <div class="email-body">
            {% if email.html_bodytext %}
                {{ email.html_bodytext|safe }}
            {% else %}
                <pre>{{ email.plain_bodytext }}</pre>
            {% endif %}
        </div>
        {% if email.attachments.exists %}
        <div class="email-attachments">
            <p><strong>{% translate "Attachments" %}:</strong></p>
            {% for attachment in email.attachments.all %}
                <div class="attachment">
                    {{ attachment.file_name }} {% if attachment.content_id %}(cid: {{ attachment.content_id }}){% endif %}
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</body>
</html>
"""

EMAIL_CSS_DEFAULT = """body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 10px;
        }
        .email-container {
            border: 1px solid #ddd;
            border-radius: 3px;
            padding: 16px;
        }
        .email-header {
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .email-subject {
            font-size: 1.5em;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .email-meta,.email-datetime {
            color: #666;
            font-size: 0.9em;
        }
        .email-body {
            margin: 20px 0;
        }
        .email-attachments {
            margin-top: 20px;
        }
        .attachment {
            margin: 5px 0;
        }"""

# If one of these defaults is changed, that change is not applied to existing default configurations
# To still apply the new default to existing servers, change the name of the setting!
CONSTANCE_CONFIG = {
    "API_DEFAULT_PAGE_SIZE": (
        20,
        _("Default page size for paginated API response data"),
        int,
    ),
    "API_MAX_PAGE_SIZE": (
        200,
        _("Maximum page size for paginated API response data"),
        int,
    ),
    "WEB_DEFAULT_PAGE_SIZE": (
        25,
        _("Default page size for pagination in the webapp."),
        int,
    ),
    "WEB_PAGE_SIZES_OPTIONS": (
        [10, 25, 50, 75, 100],
        _(
            "Page size options for pagination in the webapp. Should contain the WEB_DEFAULT_PAGE_SIZE value."
        ),
        list,
    ),
    "WEB_THUMBNAIL_MAX_DATASIZE": (
        10000000,
        _(
            "Maximum datasize for a thumbnail in the webapp. Thumbnails larger than this will not be loaded."
        ),
        int,
    ),
    "STORAGE_MAX_FILES_PER_DIR": (
        10000,
        _("Maximum numbers of files in one storage unit."),
        int,
    ),
    "THROW_OUT_SPAM": (
        True,
        _("Whether or not to ignore emails that have a spam flag"),
        bool,
    ),
    "IGNORED_MAILBOXES_REGEX": (
        "(Spam|Junk)",
        _(
            "Regex pattern (case-insensitive) for mailbox names that are ignored when looking up mailboxes in an account."
        ),
        str,
    ),
    "DONT_PARSE_CONTENT_MAINTYPES": (
        [""],
        _("List of content types prefixes to not parse as files."),
        list,
    ),
    "DONT_PARSE_CONTENT_SUBTYPES": (
        [""],
        _(
            "List of content types prefixes to not parse as files. Plain and HTML text is always ignored as its the bodytext."
        ),
        list,
    ),
    "EMAIL_HTML_TEMPLATE": (
        EMAIL_HTML_TEMPLATE_DEFAULT,
        _(
            "Html template used to render emails to html. Uses the django template syntax and has access to all fields of the email database table. Removing template tag imports may result in 500 responses when requesting pages with email thumbnails, so be careful."
        ),
        "text",
    ),
    "EMAIL_CSS": (
        EMAIL_CSS_DEFAULT,
        _(
            "Css style used to render emails to html. Refer to HTML_TEMPLATE for context on the classes."
        ),
        "text",
    ),
    "DEFAULT_SAVE_TO_EML": (
        True,
        _("Default mailbox setting whether to store mails as eml."),
        bool,
    ),
    "DEFAULT_SAVE_ATTACHMENTS": (
        True,
        _("Default mailbox setting whether to store attachments."),
        bool,
    ),
    "REGISTRATION_ENABLED": (
        True,
        _(
            "Set this to True to allow new users to sign up themselves. This setting only takes effect if the REGISTRATION_ENABLED environment setting is not 0."
        ),
        bool,
    ),
}

CONSTANCE_CONFIG_FIELDSETS = (
    (_("Server Configurations"), ("REGISTRATION_ENABLED",)),
    (
        _("Default Values"),
        (
            "DEFAULT_SAVE_TO_EML",
            "DEFAULT_SAVE_ATTACHMENTS",
        ),
    ),
    (
        _("Processing Settings"),
        (
            "THROW_OUT_SPAM",
            "IGNORED_MAILBOXES_REGEX",
            "EMAIL_HTML_TEMPLATE",
            "EMAIL_CSS",
            "DONT_PARSE_CONTENT_MAINTYPES",
            "DONT_PARSE_CONTENT_SUBTYPES",
        ),
    ),
    (
        _("Storage Settings"),
        ("STORAGE_MAX_FILES_PER_DIR",),
    ),
    (
        _("API Settings"),
        (
            "API_DEFAULT_PAGE_SIZE",
            "API_MAX_PAGE_SIZE",
        ),
    ),
    (
        _("Web Settings"),
        (
            "WEB_DEFAULT_PAGE_SIZE",
            "WEB_PAGE_SIZES_OPTIONS",
            "WEB_THUMBNAIL_MAX_DATASIZE",
        ),
    ),
)
