#!/bin/bash
source .venv/bin/activate

set -o pipefail


CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.py$')

if [ -z "$CHANGED_FILES" ]; then
  echo "No Python files in commit."
  exit 0
fi

#format

black --config=validation/black_config $CHANGED_FILES > validation/reports/black_precommit.ansi
if [ $? -ne 0 ]; then
  echo "Formatting code failed, please check validation/reports/black_precommit.ansi ."
  exit 1
fi

git add $CHANGED_FILES

# lint
pylint --rcfile=validation/pylintrc_code $CHANGED_FILES > validation/reports/pylint_code_precommit.ansi
if [ $? -ne 0 ]; then
  echo "Pylinting code failed, please check validation/reports/pylint_code_precommit.ansi ."
  exit 1
fi

pylint --rcfile=validation/pylintrc_docs $CHANGED_FILES > validation/reports/pylint_docs_precommit.ansi
if [ $? -ne 0 ]; then
  echo "Pylinting docs failed, please check validation/reports/pylint_docs_precommit.ansi ."
  exit 1
fi

pylint --rcfile=validation/pylintrc_style $CHANGED_FILES > validation/reports/pylint_style_precommit.ansi
if [ $? -ne 0 ]; then
  echo "Pylinting style failed, please check validation/reports/pylint_style_precommit.ansi ."
  exit 1
fi

echo "All precommit actions passed successfully."
exit 0
