# Generated by Django 5.2.5 on 2025-08-31 20:48

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StorageShard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shard_directory_name",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="shard directory name",
                    ),
                ),
                (
                    "file_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="file count"
                    ),
                ),
                ("current", models.BooleanField(default=False, verbose_name="current")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
            ],
            options={
                "db_table": "sharded_storage",
            },
        ),
    ]
