# Generated by Django 5.2.5 on 2025-09-04 11:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paperless_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL of your Paperless server.",
                        max_length=255,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                        verbose_name="Paperless server URL",
                    ),
                ),
                (
                    "paperless_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API key for your Paperless server.",
                        max_length=255,
                        verbose_name="Paperless server API key",
                    ),
                ),
                (
                    "paperless_tika_enabled",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Whether Tika support is enabled on your Paperless server.",
                        verbose_name="Paperless Tika support enabled",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "db_table": "user_profiles",
            },
        ),
    ]
