# Generated by Django 5.1.4 on 2025-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_configurationmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="daemon",
            name="log_backup_count",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="daemon",
            name="logfile_size",
            field=models.IntegerField(default=1048576),
        ),
    ]
