# Generated by Django 5.1.4 on 2025-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_bodytext_emailmodel_plain_bodytext_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="auto_submitted",
        ),
        migrations.RemoveField(
            model_name="email",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="email",
            name="content_language",
        ),
        migrations.RemoveField(
            model_name="email",
            name="content_location",
        ),
        migrations.RemoveField(
            model_name="email",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="email",
            name="importance",
        ),
        migrations.RemoveField(
            model_name="email",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="email",
            name="precedence",
        ),
        migrations.RemoveField(
            model_name="email",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="email",
            name="received",
        ),
        migrations.RemoveField(
            model_name="email",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="email",
            name="x_originated_client",
        ),
        migrations.RemoveField(
            model_name="email",
            name="x_priority",
        ),
        migrations.RemoveField(
            model_name="mailbox",
            name="save_images",
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_disposition",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="email",
            name="headers",
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
