# Generated by Django 5.1.4 on 2025-02-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_emailmodel_auto_submitted_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="email",
            name="email_unique_together_message_id_account",
        ),
        migrations.RemoveField(
            model_name="email",
            name="account",
        ),
        migrations.AddField(
            model_name="email",
            name="mailbox",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="core.mailbox",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.UniqueConstraint(
                fields=("message_id", "mailbox"),
                name="email_unique_together_message_id_mailbox",
            ),
        ),
    ]
