# Generated by Django 5.1.6 on 2025-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0008_remove_mailinglistmodel_mailinglist_unique_together_list_id_correspondent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="content_disposition",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="email",
            name="email_subject",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="email",
            name="html_bodytext",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="plain_bodytext",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="x_spam",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="list_archive",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="list_help",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="list_owner",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="list_post",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="list_subscribe",
            field=models.EmailField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="list_unsubscribe",
            field=models.EmailField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
