# Generated by Django 5.1.6 on 2025-03-08 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_attachmentmodel_content_disposition_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP", "IMAP"),
                    ("IMAP_SSL", "IMAP_SSL"),
                    ("POP3", "POP3"),
                    ("POP3_SSL", "POP3_SSL"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("protocol__in", ("IMAP", "IMAP_SSL", "POP3", "POP3_SSL"))
                ),
                name="protocol_valid_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="daemon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fetching_criterion__in",
                        (
                            "RECENT",
                            "UNSEEN",
                            "ALL",
                            "NEW",
                            "OLD",
                            "FLAGGED",
                            "DRAFT",
                            "ANSWERED",
                            "DAILY",
                            "WEEKLY",
                            "MONTHLY",
                            "ANNUALLY",
                        ),
                    )
                ),
                name="fetching_criterion_valid_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailcorrespondent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "mention__in",
                        (
                            "From",
                            "To",
                            "Cc",
                            "Bcc",
                            "Sender",
                            "Reply-To",
                            "Resent-From",
                            "Resent-To",
                            "Resent-Cc",
                            "Resent-Bcc",
                            "Resent-Sender",
                            "Resent-Reply-To",
                            "Envelope-To",
                            "Delivered-To",
                            "Return-Path",
                            "Return-Receipt-To",
                            "Disposition-Notification-To",
                        ),
                    )
                ),
                name="mention_criterion_valid_choice",
            ),
        ),
    ]
