# Generated by Django 5.2 on 2025-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_accountmodel_mail_host_port_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="daemon",
            name="fetching_criterion_valid_choice",
        ),
        migrations.AlterField(
            model_name="daemon",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("RECENT", "All RECENT emails"),
                    ("UNSEEN", "All UNSEEN emails"),
                    ("ALL", "All emails"),
                    ("NEW", "All RECENT and UNSEEN emails"),
                    ("OLD", "All emails that are not NEW"),
                    ("FLAGGED", "FLAGGED emails"),
                    ("DRAFT", "All email DRAFTs"),
                    ("UNDRAFT", "All emails that are not DRAFTs"),
                    ("ANSWERED", "All ANSWERED emails"),
                    ("UNANSWERED", "All UNANSWERED emails"),
                    ("DELETED", "All DELETED emails"),
                    ("UNDELETED", "All UNDELETED emails"),
                    ("DAILY", "All emails received the last DAY"),
                    ("WEEKLY", "All emails received the last WEEK"),
                    ("MONTHLY", "All emails receiced the last MONTH"),
                    ("ANNUALLY", "All emails received the last YEAR"),
                ],
                default="ALL",
                help_text="The selection criterion for emails to archive.",
                max_length=10,
                verbose_name="Fetching Criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="daemon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fetching_criterion__in",
                        [
                            "RECENT",
                            "UNSEEN",
                            "ALL",
                            "NEW",
                            "OLD",
                            "FLAGGED",
                            "DRAFT",
                            "UNDRAFT",
                            "ANSWERED",
                            "UNANSWERED",
                            "DELETED",
                            "UNDELETED",
                            "DAILY",
                            "WEEKLY",
                            "MONTHLY",
                            "ANNUALLY",
                        ],
                    )
                ),
                name="fetching_criterion_valid_choice",
            ),
        ),
    ]
