# Generated by Django 5.2 on 2025-05-04 09:21

import pathlib

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_daemonmodel_fetching_criterion_valid_choice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daemon",
            name="log_filepath",
            field=models.FilePathField(
                path=pathlib.PurePosixPath("/var/lib"), recursive=True, unique=True
            ),
        ),
    ]
