# Generated by Django 5.2 on 2025-05-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_daemonmodel_log_filepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_healthy",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="is_healthy",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="log_filepath",
            field=models.FilePathField(path="/var/lib", recursive=True, unique=True),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="is_healthy",
            field=models.BooleanField(null=True),
        ),
    ]
