# Generated by Django 5.2 on 2025-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_accountmodel_is_healthy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="content_type",
            new_name="content_maintype",
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_subtype",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="log_filepath",
            field=models.FilePathField(path="/var/log", recursive=True, unique=True),
        ),
    ]
