# Generated by Django 5.2.1 on 2025-05-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_daemonmodel_fetching_criterion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="inReplyTo",
            new_name="in_reply_to",
        ),
        migrations.RenameField(
            model_name="mailbox",
            old_name="save_toEML",
            new_name="save_to_eml",
        ),
        migrations.RenameField(
            model_name="mailbox",
            old_name="save_toHTML",
            new_name="save_to_html",
        ),
    ]
