# Generated by Django 5.2.1 on 2025-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_account_protocol_valid_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="references",
            field=models.ManyToManyField(related_name="referenced_by", to="core.email"),
        ),
    ]
