# Generated by Django 5.2.1 on 2025-05-23 16:48

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_email_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageShard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shard_directory_name",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file_count", models.PositiveSmallIntegerField(default=0)),
                ("current", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_shards",
            },
        ),
        migrations.DeleteModel(
            name="Storage",
        ),
        migrations.RemoveConstraint(
            model_name="attachment",
            name="attachment_unique_together_file_path_email",
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_path",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="eml_filepath",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="html_filepath",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="message_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
