# Generated by Django 5.2.1 on 2025-06-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_remove_email_in_reply_to_email_in_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="html_filepath",
        ),
        migrations.RemoveField(
            model_name="mailbox",
            name="save_to_html",
        ),
        migrations.AddField(
            model_name="email",
            name="html_version",
            field=models.TextField(blank=True, default=""),
        ),
    ]
