# Generated by Django 5.2.1 on 2025-06-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_email_html_filepath_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daemon",
            name="cycle_interval",
        ),
        migrations.RemoveField(
            model_name="daemon",
            name="is_running",
        ),
        migrations.RemoveField(
            model_name="daemon",
            name="restart_time",
        ),
        migrations.AddField(
            model_name="daemon",
            name="celery_task",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="daemon",
            name="interval",
            field=models.ForeignKey(
                default=1,
                help_text="The time between two daemon runs in seconds.",
                on_delete=django.db.models.deletion.PROTECT,
                to="django_celery_beat.intervalschedule",
                verbose_name="Fetching Interval",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="daemon",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "fetching_criterion"),
                name="daemon_unique_together_mailbox_fetching_criterion",
            ),
        ),
    ]
