# Generated by Django 5.2.1 on 2025-06-16 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_email_mailinglist_correspondent_list_archive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="mail_host_port",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The port of the mailserver for the chosen protocol.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(65535)],
                verbose_name="Mailserver-Portnumber",
            ),
        ),
    ]
