# Generated by Django 5.2.1 on 2025-06-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_account_mail_host_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daemon",
            name="log_filepath",
            field=models.FilePathField(
                path="/var/log/emailkasten", recursive=True, unique=True
            ),
        ),
    ]
