# Generated by Django 5.2.3 on 2025-07-01 19:06

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_daemon_log_filepath"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_healthy",
            field=models.BooleanField(null=True, verbose_name="healthy"),
        ),
        migrations.AlterField(
            model_name="account",
            name="mail_address",
            field=models.EmailField(
                help_text="The mail address to the account.",
                max_length=255,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="mail_host",
            field=models.CharField(
                help_text="The URL of the mailserver for the chosen protocol.",
                max_length=255,
                verbose_name="mailserver URL",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="mail_host_port",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The port of the mailserver for the chosen protocol.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(65535)],
                verbose_name="mailserver portnumber",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(
                help_text="The password to the account.",
                max_length=255,
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP", "IMAP4"),
                    ("IMAP4_SSL", "IMAP4 over SSL"),
                    ("POP3", "POP3"),
                    ("POP3_SSL", "POP3 over SSL"),
                ],
                help_text="The email protocol implemented by the server.",
                max_length=10,
                verbose_name="email protocol",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="timeout",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Timeout for the connection to the mailserver.",
                null=True,
                verbose_name="connection timeout",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="content_disposition",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="content disposition",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="content_id",
            field=models.CharField(
                default="", max_length=255, verbose_name="content ID"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="content_maintype",
            field=models.CharField(
                default="", max_length=255, verbose_name="content maintype"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="content_subtype",
            field=models.CharField(
                default="", max_length=255, verbose_name="content subtype"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="datasize",
            field=models.PositiveIntegerField(verbose_name="datasize"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="core.email",
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_name",
            field=models.CharField(max_length=255, verbose_name="filename"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_path",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="filepath",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="email_address",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="email_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The mailer name of the correspondent.",
                max_length=255,
                verbose_name="mailer name",
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_archive",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="list archive"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_help",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="list help"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="list ID"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_owner",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="list owner"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_post",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="list post"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_subscribe",
            field=models.EmailField(
                blank=True, default="", max_length=255, verbose_name="list subscribe"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_unsubscribe",
            field=models.EmailField(
                blank=True, default="", max_length=255, verbose_name="list unsubscribe"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="celery_task",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
                verbose_name="celery task",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("RECENT", "All RECENT emails"),
                    ("UNSEEN", "All UNSEEN emails"),
                    ("ALL", "All emails"),
                    ("NEW", "All RECENT and UNSEEN emails"),
                    ("OLD", "All emails that are not NEW"),
                    ("FLAGGED", "FLAGGED emails"),
                    ("DRAFT", "All email DRAFTs"),
                    ("UNDRAFT", "All emails that are not DRAFTs"),
                    ("ANSWERED", "All ANSWERED emails"),
                    ("UNANSWERED", "All UNANSWERED emails"),
                    ("DELETED", "All DELETED emails"),
                    ("UNDELETED", "All UNDELETED emails"),
                    ("DAILY", "All emails received the last DAY"),
                    ("WEEKLY", "All emails received the last WEEK"),
                    ("MONTHLY", "All emails receiced the last MONTH"),
                    ("ANNUALLY", "All emails received the last YEAR"),
                ],
                default="ALL",
                help_text="The selection criterion for emails to archive.",
                max_length=127,
                verbose_name="fetching criterion",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="interval",
            field=models.ForeignKey(
                help_text="The time between two daemon runs in seconds.",
                on_delete=django.db.models.deletion.PROTECT,
                to="django_celery_beat.intervalschedule",
                verbose_name="interval",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="is_healthy",
            field=models.BooleanField(null=True, verbose_name="healthy"),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="log_backup_count",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="The number of historical logfiles to keep.",
                verbose_name="logfile backup count",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="log_filepath",
            field=models.FilePathField(
                path="/var/log/emailkasten",
                recursive=True,
                unique=True,
                verbose_name="logfilepath",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="logfile_size",
            field=models.PositiveIntegerField(
                default=1048576,
                help_text="The maximum size of a logfile in bytes.",
                verbose_name="logfile maximum size",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daemons",
                to="core.mailbox",
                verbose_name="mailbox",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="correspondents",
            field=models.ManyToManyField(
                related_name="emails",
                through="core.EmailCorrespondent",
                to="core.correspondent",
                verbose_name="correspondents",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="email",
            name="datasize",
            field=models.PositiveIntegerField(verbose_name="datasize"),
        ),
        migrations.AlterField(
            model_name="email",
            name="datetime",
            field=models.DateTimeField(verbose_name="received"),
        ),
        migrations.AlterField(
            model_name="email",
            name="email_subject",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subject"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="eml_filepath",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="EML filepath",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="headers",
            field=models.JSONField(null=True, verbose_name="headers"),
        ),
        migrations.AlterField(
            model_name="email",
            name="html_bodytext",
            field=models.TextField(
                blank=True, default="", verbose_name="HTML bodytext"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="html_version",
            field=models.TextField(blank=True, default="", verbose_name="HTML version"),
        ),
        migrations.AlterField(
            model_name="email",
            name="in_reply_to",
            field=models.ManyToManyField(
                related_name="replies", to="core.email", verbose_name="in reply to"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite"),
        ),
        migrations.AlterField(
            model_name="email",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="core.mailbox",
                verbose_name="mailbox",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="message_id",
            field=models.CharField(max_length=255, verbose_name="message-ID"),
        ),
        migrations.AlterField(
            model_name="email",
            name="plain_bodytext",
            field=models.TextField(
                blank=True, default="", verbose_name="plain bodytext"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="references",
            field=models.ManyToManyField(
                related_name="referenced_by",
                to="core.email",
                verbose_name="referenced by",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="email",
            name="x_spam",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="X-Spam"
            ),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="correspondent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correspondentemails",
                to="core.correspondent",
                verbose_name="correspondent",
            ),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emailcorrespondents",
                to="core.email",
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="mention",
            field=models.CharField(
                choices=[
                    ("From", "From"),
                    ("To", "To"),
                    ("Cc", "CC"),
                    ("Bcc", "BCC"),
                    ("Sender", "Sender"),
                    ("Reply-To", "Reply-To"),
                    ("Resent-From", "Resent-From"),
                    ("Resent-To", "Resent-To"),
                    ("Resent-Cc", "Resent-Cc"),
                    ("Resent-Bcc", "Resent-Bcc"),
                    ("Resent-Sender", "Resent-Sender"),
                    ("Resent-Reply-To", "Resent-Reply-To"),
                    ("Envelope-To", "Envelope-To"),
                    ("Delivered-To", "Delivered-To"),
                    ("Return-Path", "Return-Path"),
                    ("Return-Receipt-To", "Return-Receipt-To"),
                    ("Disposition-Notification-To", "Disposition-Notification-To"),
                ],
                max_length=30,
                verbose_name="mention",
            ),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailboxes",
                to="core.account",
                verbose_name="account",
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="is_healthy",
            field=models.BooleanField(null=True, verbose_name="healthy"),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="save_attachments",
            field=models.BooleanField(
                default=True,
                help_text="Whether the attachments from the emails in this mailbox will be saved.",
                verbose_name="save attachments",
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="save_to_eml",
            field=models.BooleanField(
                default=True,
                help_text="Whether the emails in this mailbox will be stored in .eml files.",
                verbose_name="save as .eml",
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="current",
            field=models.BooleanField(default=False, verbose_name="current"),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="file_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="file count"
            ),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="shard_directory_name",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="shard directory name",
            ),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
    ]
