# Generated by Django 5.2.3 on 2025-07-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_account_created_alter_account_is_favorite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondent",
            name="email_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The mailer name of the correspondent.",
                verbose_name="mailer name",
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_archive",
            field=models.TextField(blank=True, default="", verbose_name="list archive"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_help",
            field=models.TextField(blank=True, default="", verbose_name="list help"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_id",
            field=models.TextField(blank=True, default="", verbose_name="list ID"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_owner",
            field=models.TextField(blank=True, default="", verbose_name="list owner"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_post",
            field=models.TextField(blank=True, default="", verbose_name="list post"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_subscribe",
            field=models.TextField(
                blank=True, default="", verbose_name="list subscribe"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_unsubscribe",
            field=models.TextField(
                blank=True, default="", verbose_name="list unsubscribe"
            ),
        ),
    ]
