# Generated by Django 5.2.3 on 2025-07-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_correspondent_list_unsubscribe_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="html_version",
        ),
    ]
