# Generated by Django 5.2.3 on 2025-07-14 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_email_html_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondent",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="email_address",
            field=models.CharField(max_length=255, verbose_name="email address"),
        ),
        migrations.AddConstraint(
            model_name="correspondent",
            constraint=models.UniqueConstraint(
                fields=("email_address", "user"),
                name="email_unique_together_email_address_user",
            ),
        ),
    ]
