# Generated by Django 5.2.3 on 2025-07-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_correspondent_user_alter_correspondent_email_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondent",
            name="real_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The real name of the correspondent.",
                max_length=255,
                verbose_name="real name",
            ),
        ),
    ]
