# Generated by Django 5.2.3 on 2025-07-15 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_correspondent_real_name"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="protocol_valid_choice",
        ),
        migrations.RemoveConstraint(
            model_name="daemon",
            name="fetching_criterion_valid_choice",
        ),
        migrations.AlterField(
            model_name="account",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP", "IMAP4"),
                    ("IMAP4_SSL", "IMAP4 over SSL"),
                    ("POP3", "POP3"),
                    ("POP3_SSL", "POP3 over SSL"),
                    ("EXCHANGE", "Microsoft Exchange"),
                ],
                help_text="The email protocol implemented by the server.",
                max_length=10,
                verbose_name="email protocol",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("RECENT", "All RECENT emails"),
                    ("UNSEEN", "All UNSEEN emails"),
                    ("SEEN", "All SEEN emails"),
                    ("ALL", "All emails"),
                    ("NEW", "All RECENT and UNSEEN emails"),
                    ("OLD", "All emails that are not RECENT"),
                    ("FLAGGED", "FLAGGED emails"),
                    ("DRAFT", "All email DRAFTs"),
                    ("UNDRAFT", "All emails that are not DRAFTs"),
                    ("ANSWERED", "All ANSWERED emails"),
                    ("UNANSWERED", "All UNANSWERED emails"),
                    ("DELETED", "All DELETED emails"),
                    ("UNDELETED", "All UNDELETED emails"),
                    ("DAILY", "All emails received the last DAY"),
                    ("WEEKLY", "All emails received the last WEEK"),
                    ("MONTHLY", "All emails receiced the last MONTH"),
                    ("ANNUALLY", "All emails received the last YEAR"),
                ],
                default="ALL",
                help_text="The selection criterion for emails to archive.",
                max_length=127,
                verbose_name="fetching criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "protocol__in",
                        ["IMAP", "IMAP4_SSL", "POP3", "POP3_SSL", "EXCHANGE"],
                    )
                ),
                name="protocol_valid_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="daemon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fetching_criterion__in",
                        [
                            "RECENT",
                            "UNSEEN",
                            "SEEN",
                            "ALL",
                            "NEW",
                            "OLD",
                            "FLAGGED",
                            "DRAFT",
                            "UNDRAFT",
                            "ANSWERED",
                            "UNANSWERED",
                            "DELETED",
                            "UNDELETED",
                            "DAILY",
                            "WEEKLY",
                            "MONTHLY",
                            "ANNUALLY",
                        ],
                    )
                ),
                name="fetching_criterion_valid_choice",
            ),
        ),
    ]
