# Generated by Django 5.2.4 on 2025-07-31 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_daemon_log_filepath"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="protocol_valid_choice",
        ),
        migrations.AlterField(
            model_name="account",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP4_SSL", "IMAP4"),
                    ("IMAP", "IMAP4 (unencrypted)"),
                    ("POP3_SSL", "POP3"),
                    ("POP3", "POP3  (unencrypted)"),
                    ("EXCHANGE", "Microsoft Exchange"),
                ],
                help_text="The email protocol implemented by the server.",
                max_length=10,
                verbose_name="email protocol",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "protocol__in",
                        ["IMAP4_SSL", "IMAP", "POP3_SSL", "POP3", "EXCHANGE"],
                    )
                ),
                name="protocol_valid_choice",
            ),
        ),
    ]
