# Generated by Django 5.2.4 on 2025-08-05 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_remove_account_protocol_valid_choice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="account_unique_together_mail_address_user",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("mail_address", "protocol", "user"),
                name="account_unique_together_mail_address_protocol_user",
            ),
        ),
    ]
