# Generated by Django 5.2.5 on 2025-08-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0041_remove_account_account_unique_together_mail_address_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daemon",
            name="log_backup_count",
        ),
        migrations.RemoveField(
            model_name="daemon",
            name="log_filepath",
        ),
        migrations.RemoveField(
            model_name="daemon",
            name="logfile_size",
        ),
        migrations.AddField(
            model_name="daemon",
            name="last_error",
            field=models.TextField(blank=True, default="", verbose_name="last error"),
        ),
    ]
