# Generated by Django 5.2.5 on 2025-08-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_remove_daemon_log_backup_count_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StorageShard",
        ),
    ]
