# Generated by Django 5.2.5 on 2025-09-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_account_last_error_account_last_error_occurred_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "get_latest_by": "created",
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "get_latest_by": "email__datetime",
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="correspondent",
            options={
                "get_latest_by": "created",
                "verbose_name": "correspondent",
                "verbose_name_plural": "correspondents",
            },
        ),
        migrations.AlterModelOptions(
            name="daemon",
            options={
                "get_latest_by": "created",
                "verbose_name": "daemon",
                "verbose_name_plural": "daemons",
            },
        ),
        migrations.AlterModelOptions(
            name="email",
            options={
                "get_latest_by": "datetime",
                "verbose_name": "email",
                "verbose_name_plural": "emails",
            },
        ),
        migrations.AlterModelOptions(
            name="emailcorrespondent",
            options={
                "get_latest_by": "created",
                "verbose_name": "email-correspondents",
            },
        ),
        migrations.AlterModelOptions(
            name="mailbox",
            options={
                "get_latest_by": "created",
                "verbose_name": "mailbox",
                "verbose_name_plural": "mailboxes",
            },
        ),
        migrations.AlterModelOptions(
            name="storageshard",
            options={
                "verbose_name": "storage shard",
                "verbose_name_plural": "storage shards",
            },
        ),
        migrations.RenameField(
            model_name="email",
            old_name="email_subject",
            new_name="subject",
        ),
        migrations.AlterField(
            model_name="account",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite status"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_healthy",
            field=models.BooleanField(null=True, verbose_name="health status"),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite status"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite status"),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_subscribe",
            field=models.TextField(
                blank=True, default="", verbose_name="list-subscribe"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_unsubscribe",
            field=models.TextField(
                blank=True, default="", verbose_name="list-unsubscribe"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="list_unsubscribe_post",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="list-unsubscribe method",
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="is_healthy",
            field=models.BooleanField(null=True, verbose_name="health status"),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="datetime",
            field=models.DateTimeField(verbose_name="time received"),
        ),
        migrations.AlterField(
            model_name="email",
            name="in_reply_to",
            field=models.ManyToManyField(
                related_name="replies",
                to="core.email",
                verbose_name="in reply to email",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite status"),
        ),
        migrations.AlterField(
            model_name="email",
            name="references",
            field=models.ManyToManyField(
                related_name="referenced_by",
                to="core.email",
                verbose_name="referencing emails",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="x_spam",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="X-Spam Flag"
            ),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="emailcorrespondent",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="favorite status"),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="is_healthy",
            field=models.BooleanField(null=True, verbose_name="health status"),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="current",
            field=models.BooleanField(default=False, verbose_name="status"),
        ),
        migrations.AlterField(
            model_name="storageshard",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="time of last update"
            ),
        ),
    ]
