# Generated by Django 5.2.5 on 2025-09-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_account_options_alter_attachment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="eml_filepath",
            new_name="file_path",
        ),
    ]
