# Generated by Django 5.2.5 on 2025-09-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_rename_email_eml_filepath_email_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="file_path",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="filepath",
            ),
        ),
    ]
