# Generated by Django 5.2.6 on 2025-09-29 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_email_file_path"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="daemon",
            options={
                "get_latest_by": "created",
                "verbose_name": "routine",
                "verbose_name_plural": "routines",
            },
        ),
        migrations.AlterField(
            model_name="daemon",
            name="interval",
            field=models.ForeignKey(
                help_text="The time between two routine runs in seconds.",
                on_delete=django.db.models.deletion.PROTECT,
                to="django_celery_beat.intervalschedule",
                verbose_name="interval",
            ),
        ),
    ]
