# Generated by Django 5.2.7 on 2025-10-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_daemon_options_alter_daemon_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.TextField(blank=True, default="", verbose_name="subject"),
        ),
    ]
