# Generated by Django 5.2.7 on 2025-10-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_email_subject"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="daemon",
            name="fetching_criterion_valid_choice",
        ),
        migrations.AlterField(
            model_name="daemon",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("DAILY", "All emails received the last DAY"),
                    ("WEEKLY", "All emails received the last WEEK"),
                    ("MONTHLY", "All emails receiced the last MONTH"),
                    ("ANNUALLY", "All emails received the last YEAR"),
                    ("RECENT", "All RECENT emails"),
                    ("UNSEEN", "All UNSEEN emails"),
                    ("SEEN", "All SEEN emails"),
                    ("ALL", "All emails"),
                    ("NEW", "All RECENT and UNSEEN emails"),
                    ("OLD", "All emails that are not RECENT"),
                    ("FLAGGED", "FLAGGED emails"),
                    ("DRAFT", "All email DRAFTs"),
                    ("UNDRAFT", "All emails that are not DRAFTs"),
                    ("ANSWERED", "All ANSWERED emails"),
                    ("UNANSWERED", "All UNANSWERED emails"),
                    ("DELETED", "All DELETED emails"),
                    ("UNDELETED", "All UNDELETED emails"),
                ],
                default="ALL",
                help_text="The selection criterion for emails to archive.",
                max_length=127,
                verbose_name="fetching criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="daemon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fetching_criterion__in",
                        [
                            "DAILY",
                            "WEEKLY",
                            "MONTHLY",
                            "ANNUALLY",
                            "RECENT",
                            "UNSEEN",
                            "SEEN",
                            "ALL",
                            "NEW",
                            "OLD",
                            "FLAGGED",
                            "DRAFT",
                            "UNDRAFT",
                            "ANSWERED",
                            "UNANSWERED",
                            "DELETED",
                            "UNDELETED",
                        ],
                    )
                ),
                name="fetching_criterion_valid_choice",
            ),
        ),
    ]
