# Generated by Django 5.2.7 on 2025-11-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_remove_daemon_fetching_criterion_valid_choice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("IMAP4_SSL", "IMAP4"),
                    ("IMAP", "IMAP4 (unencrypted)"),
                    ("POP3_SSL", "POP3"),
                    ("POP3", "POP3 (unencrypted)"),
                    ("EXCHANGE", "Microsoft Exchange"),
                ],
                help_text="The email protocol implemented by the server.",
                max_length=10,
                verbose_name="email protocol",
            ),
        ),
    ]
