# Generated by Django 5.2.8 on 2025-11-08 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_account_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="timeout",
            field=models.PositiveIntegerField(
                blank=True,
                default=10,
                help_text="Timeout for the connection to the mailserver.",
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="connection timeout",
            ),
        ),
    ]
