# Generated by Django 5.2.8 on 2025-11-19 17:45

from django.db import migrations, models


def convert_flag_str_to_nullbool(apps, schema_editor):
    Email = apps.get_model("core", "Email")
    for item in Email.objects.all():
        item.x_spam_flag = (
            ("YES" in item.x_spam) if item.x_spam else None
        )  # see utils.is_x_spam
        item.save(update_fields=["x_spam_flag"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_alter_account_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="x_spam_flag",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="X-Spam Flag"
            ),
        ),
        migrations.RunPython(convert_flag_str_to_nullbool),
        migrations.RemoveField(
            model_name="email",
            name="x_spam",
        ),
    ]
