# Generated by Django 5.2.8 on 2025-12-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_remove_email_x_spam_email_x_spam_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_favorite",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="favorite status"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_healthy",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="health status"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_error_occurred_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="time of last error occurrence"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="is_favorite",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="favorite status"
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="is_favorite",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="favorite status"
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("DAILY", "All emails received the last DAY"),
                    ("WEEKLY", "All emails received the last WEEK"),
                    ("MONTHLY", "All emails received the last MONTH"),
                    ("ANNUALLY", "All emails received the last YEAR"),
                    ("RECENT", "All RECENT emails"),
                    ("UNSEEN", "All UNSEEN emails"),
                    ("SEEN", "All SEEN emails"),
                    ("ALL", "All emails"),
                    ("NEW", "All RECENT and UNSEEN emails"),
                    ("OLD", "All emails that are not RECENT"),
                    ("FLAGGED", "FLAGGED emails"),
                    ("DRAFT", "All email DRAFTs"),
                    ("UNDRAFT", "All emails that are not DRAFTs"),
                    ("ANSWERED", "All ANSWERED emails"),
                    ("UNANSWERED", "All UNANSWERED emails"),
                    ("DELETED", "All DELETED emails"),
                    ("UNDELETED", "All UNDELETED emails"),
                ],
                default="ALL",
                help_text="The selection criterion for emails to archive.",
                max_length=127,
                verbose_name="fetching criterion",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="is_healthy",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="health status"
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="last_error_occurred_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="time of last error occurrence"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="is_favorite",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="favorite status"
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="is_favorite",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="favorite status"
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="is_healthy",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="health status"
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="last_error_occurred_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="time of last error occurrence"
            ),
        ),
    ]
