# Generated by Django 5.2.9 on 2025-12-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_remove_daemon_fetching_criterion_valid_choice_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="daemon",
            name="fetching_criterion_valid_choice",
        ),
        migrations.AddField(
            model_name="daemon",
            name="fetching_criterion_arg",
            field=models.CharField(
                default="",
                help_text="Additional value for the selection criterion.",
                max_length=255,
                verbose_name="filter value",
            ),
        ),
        migrations.AlterField(
            model_name="daemon",
            name="fetching_criterion",
            field=models.CharField(
                choices=[
                    ("DAILY", "All emails received the last DAY"),
                    ("WEEKLY", "All emails received the last WEEK"),
                    ("MONTHLY", "All emails received the last MONTH"),
                    ("ANNUALLY", "All emails received the last YEAR"),
                    ("RECENT", "All RECENT emails"),
                    ("UNSEEN", "All UNSEEN emails"),
                    ("SEEN", "All SEEN emails"),
                    ("ALL", "All emails"),
                    ("NEW", "All RECENT and UNSEEN emails"),
                    ("OLD", "All emails that are not RECENT"),
                    ("FLAGGED", "FLAGGED emails"),
                    ("UNFLAGGED", "All emails that are not FLAGGED"),
                    ("DRAFT", "All email DRAFTs"),
                    ("UNDRAFT", "All emails that are not DRAFTs"),
                    ("ANSWERED", "All ANSWERED emails"),
                    ("UNANSWERED", "All UNANSWERED emails"),
                    ("DELETED", "All DELETED emails"),
                    ("UNDELETED", "All UNDELETED emails"),
                    ("KEYWORD {}", "All emails with the given KEYWORD"),
                    ("UNKEYWORD {}", "All emails without the given KEYWORD"),
                    ("LARGER {}", "All emails LARGER than the given size"),
                    ("SMALLER {}", "All emails SMALLER than the given size"),
                    ("SUBJECT {}", "All emails with SUBJECT containing the given text"),
                    ("BODY {}", "All emails with BODY containing the given text"),
                    ("FROM {}", "All emails sent FROM the given address"),
                    ("SENTSINCE {}", "All emails SENT SINCE the given date"),
                ],
                default="ALL",
                help_text="The selection criterion for emails to archive.",
                max_length=127,
                verbose_name="fetching criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="daemon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fetching_criterion__in",
                        [
                            "DAILY",
                            "WEEKLY",
                            "MONTHLY",
                            "ANNUALLY",
                            "RECENT",
                            "UNSEEN",
                            "SEEN",
                            "ALL",
                            "NEW",
                            "OLD",
                            "FLAGGED",
                            "UNFLAGGED",
                            "DRAFT",
                            "UNDRAFT",
                            "ANSWERED",
                            "UNANSWERED",
                            "DELETED",
                            "UNDELETED",
                            "KEYWORD {}",
                            "UNKEYWORD {}",
                            "LARGER {}",
                            "SMALLER {}",
                            "SUBJECT {}",
                            "BODY {}",
                            "FROM {}",
                            "SENTSINCE {}",
                        ],
                    )
                ),
                name="fetching_criterion_valid_choice",
            ),
        ),
    ]
