# Generated by Django 5.2.9 on 2026-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_remove_account_protocol_valid_choice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="mail_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The username of the account. Typically the mail address.",
                max_length=255,
                verbose_name="username",
            ),
        ),
    ]
