# Generated by Django 5.2.9 on 2026-01-03 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_alter_account_mail_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="account_unique_together_mail_address_protocol_user",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("mail_address", "password", "protocol", "user"),
                name="account_unique_together_mail_address_password_protocol_user",
            ),
        ),
    ]
