# Generated by Django 5.2.10 on 2026-01-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0060_remove_account_account_unique_together_mail_address_protocol_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="type",
            field=models.CharField(
                choices=[
                    ("INBOX", "Inbox"),
                    ("OUTBOX", "Outbox"),
                    ("SENT", "Sent"),
                    ("JUNK", "Junk"),
                    ("DRAFTS", "Drafts"),
                    ("TRASH", "Trash"),
                    ("", ""),
                ],
                default="",
                max_length=32,
                verbose_name="type",
            ),
        ),
    ]
