# Generated by Django 5.2.10 on 2026-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_mailbox_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="allow_insecure_connection",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Whether to allow insecure connection to the host, e.g. with a self-signed certificate.",
                verbose_name="allow insecure connection",
            ),
        ),
    ]
